### ISSUE TITLE
[Suggestion] Type safety for ComponentIds

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#114]
I'd really like to see some kind of type safety applied to the component ids, which are now just const ints.

For most use cases, I don't think end users will care too much about this, but in the case of users who dive a little deeper and great more involved systems or code that need to deal with components generically, I think additional type safety would be a boon.

For instance, I have an abstract base class that deals with components generically,
```csharp
public abstract class TimedSystem<T> : ISetPool 
    where T: ITimerComponent, new()
{
    protected abstract int TimerComponentId { get; }  
}
```

I actually have two issues here.

1. There is no guarantee that the int returned by the implementor `TimerComponentId` is an int that is an actual component id.
2. There is no way to get a component id from a component type, which would eliminate the need to even have to implement `TimerComponentId`.

I'm not sure of the performance implications, but it is possible to store int with an enum, either by adding additional data to the enum or using an implicit ordinal (which is kind of dangerous).

Thoughts?

**Comment by sschmid** [comment]
You can do Array.IndexOf with [ComponentIds.componentTypes](https://github.com/sschmid/Entitas-CSharp/blob/master/Readme/Readme/Generated/ComponentIds.cs#L34) to infer the index of a given component type.
I can also imagine to additionally generate ComponentIds.ComponentTypeToInt(type) which would be faster than Array.IndexOf

An int based enum would provide type-safety, but I need to test if there are performance drawbacks because we'd have to cast to int all the time. I can imagine that this might have a negative effect

**Comment by JamesMcMahon** [comment]
Make sense. In terms of thing TODO this would be pretty low impact / priority. Just one of things that stood out at me when looking at the generated code.

**Comment by dkozlovtsev** [comment]
Encountered the same problem trying to generalize one of my system.
As to implementation you can require(maybe optional requirement) to make IComponent implementation partial and add GetComponentId to it during generation(along with adding additional interaface in order to make new components compilable in the first place).

**Comment by JamesMcMahon** [comment]
This is what I ended up doing in my game:

```csharp
using Entitas;
using System;

public static class EntitasHelpers
{
    public static int GetComponentId(Type type)
    {
        return Array.IndexOf(ComponentIds.componentTypes, type);
    }
}
```

Then in generic base system I do:

```csharp
int? _componentId;

int TimerComponentId
{
    get
    {
        if (_componentId == null)
        {
            _componentId = EntitasHelpers.GetComponentId(typeof(T));
        }
        return _componentId.Value;
    }
}
```

I also ensure that `T` is an IComponent.

This always me to work with a component at a generic level without having to worry about the type safety of the component id.

I think this is a pretty good work around and the additional type safety of an enum probably wouldn't be worth the performance hit.
