### ISSUE TITLE
[Suggestion] Two stage initialization

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#119]
Hello again, I bet your sick of my suggestions by this point 😄 

Unity's `MonoBehavior`s have an `Awake` and `Start` method, `Awake` is always called in all scripts before `Start`, this allows two stages of initialization which makes scripts less dependent on execution order. Scripts with dependencies on other started scripts can use `Start` to ensure they have already called their `Awake` code.

One thing I've noticed is that Entitas' initializing systems are very dependent on order. I think more flexibility could be introduced by have two initialization methods, one that is guaranteed to run after the previous initialization method is run on all systems.

Thoughts?

**Comment by JuDelCo** [comment]
You could make a new derived class from [ISystem](https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/Interfaces/ISystem.cs) and add a custom method "Awake()", then derive [Systems](https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/Systems.cs) class and implement the same like Initialize (adding a new protected List, extending the constructor, extending `Add` method and adding your new Awake method).

**Comment by JamesMcMahon** [comment]
There are ways around this, like you set listeners that you want to be registered before any component creation in the `SetPool` method. That seemed like the wrong way to do things though.

Since Entitas is so interface based I think using extending concrete classes would be really limiting design wise, that's why I suggested this for inclusion in the framework itself.

It would be pretty easy to implement I think, just add new method to IInitializeSystem and then call that in the systems Initialize code. I can put a PR if people feel it's a good idea.

**Comment by dkozlovtsev** [comment]
In Unity Awake/Start separation is needed to compensate for lack of the constuctor. In Entitas your systems have a constuctor(hence the Awake phase) and Initialize function(Start method).
I personally think that even IInitialiseSystem is not needed and exists only to support ISetPool, which exists only to avoid passing pool in the constuctor, to support Pool.AddSystem<TSystem> syntax

just my 2 cents

**Comment by JamesMcMahon** [comment]
I don't think I agree. The constructor for systems is borderline useless as you don't have access to any of the larger state or the pool at that point.

So here is a straightforward example. Registering component listeners (OnEntityAdded). Right now you if you create a component in a system on initialization before another system that is listening to that component it will miss that initial add event.

You can work around that by either:

- Make sure your listener systems are there before component creation. This gets tricky in practice and can break easily when you add new systems or do any re-ordering.
-  Do a check in the listening system to see if a component is already added. I often do this just for robust sakes, but it feels like a lot of fiddling that could be avoided with a two stage init.

**Comment by sschmid** [comment]
You can create a constructor that has the pool as an argument or use ISetPool, which can basically be considered Awake() as it will be called after the System has been created (like @dkozlovtsev said)

Example for constructor with pool: [ProcessMoveInputSystem.cs](https://github.com/sschmid/Entitas-Shmup/blob/master/Assets/Sources/Features/Input/ProcessMoveInputSystem.cs#L18-L20)

I caught myself caching groups in `_myGroupXyz` fields and adding group.OnEntityAdded += in ISetPool or constructors as well, but I'd like to tell you that in an ideal case you should but this logic into Initialize().
The reason is, if you ever want to soft-restart the game (and therefore use pool.Reset()), meaning you reuse pools and all systems, but destroy all entities and get rid of all the state, all groups will be cleared and all registered event handlers will be removed. The groups also get removed from the pool completely.
Just by calling Initialize() you can re-setup all listeners and the application works as expected. If this logic is in the constructor or SetPool you cannot re-add all listeners.

Back to your question; does it help putting your logic to SetPool?
One more thought:
group.OnEntityAdded += is basically some kind of observer pattern, and I think it's ok to do these 2 steps you described:
1. Register an event handler for change
2. Process the initial state (events you potentially missed before)

I do basically the same in the [ScoreLabelController.cs](https://github.com/sschmid/Match-One/blob/master/Assets/Scripts/ScoreLabelController.cs#L12-L13) from [Match-One](https://github.com/sschmid/Match-One)

**Comment by JamesMcMahon** [comment]
> I caught myself caching groups in _myGroupXyz fields and adding group.OnEntityAdded += in ISetPool or constructors as well, but I'd like to tell you that in an ideal case you should but this logic into Initialize().

Yup, [we actually had a discussion about this awhile back](https://github.com/sschmid/Entitas-CSharp/issues/82), that's one of the reasons I don't want to use `SetPool` or the constructor.

> Back to your question; does it help putting your logic to SetPool?

I am not having a specific problem per say, but I have been working with Entitas pretty seriously over the last few months and thought I would suggest things that could be improved upon / discussed.

**Comment by mzaks** [comment]
Hm here are my 5 cents to this issue:

Unity needs two phase initialisation because game object encapsulate data and behaviour.
Entitas system encapsulate behaviour and should have no data. Therefor there is no need to have two phase initialisation.

Let me explain by example.

Say we have three systems A, B, C and we decide that we want two have second phase initialisation on A and C.

This means that on init we will have following execution order

A -> B -> C -> A -> C

This is confusing, why not introduce systems D and E to make it more explicit.

A -> B -> C -> D -> E

Now why does Unity can't do this? Because as I mentioned before Unities game object store data. Data could have cyclic references, so data in game object A is dependent on data in game object C. So after we initialised C we want to have second phase initialisation on game object A.
If you follow the strict ECS principal - separation of data and behaviour, you should not have such problems.

Or am I missing something?

**Comment by JamesMcMahon** [comment]
The use case would be that if System A creates a entity on init that B is listening to. You could reorder them, but what if B creates an entity that A is listening to.

With the two stage system A and B could register their listeners and in the second stage create their entities.

If SetPool was called again when reseting Entitas it could be used as the first stage, since it's called before initialize.

**Comment by mzaks** [comment]
You see that this happens because your systems suppose to do more than one thing 😜
