### ISSUE TITLE
[Question] ReactiveSystem execution creates a tiny garbage 

### ISSUE THREAD

**Issue by DanijelC** [sschmid/Entitas-CSharp#130]
Hi,
first of all, I would like to thank you for making a great product and putting it open sourced.

I noticed that every execution of ReactiveSystem produces a garbage of 48B on my Android phone. 
The price of tiny garbage even per frame is not a big deal for having ReactiveSystem, but in some cases can cause hiccups on mobile phone. 
For example, making replay system, like you have in your reactive project on your presentation. The replay system emulates past by going trough all logic systems for every tick and produce a lot of garbage by triggering reactive systems.

Is it possible to make ReactiveSystem free of garbage in the future?

**Comment by JuDelCo** [comment]
Maybe it's because of the foreachs in them

![](https://i.imgur.com/B38rG9i.png)

Anyway Unity it's working on a new compiler version that will fix those issues:

http://forum.unity3d.com/threads/upgraded-c-compiler-on-5-3-5p8.417363/
http://stackoverflow.com/questions/18552669/memory-allocation-when-using-foreach-loops-in-c-sharp

**Comment by sschmid** [comment]
<img width="648" alt="reactive system" src="https://cloud.githubusercontent.com/assets/233700/17461882/d1bb5f52-5c9a-11e6-88c9-7d3c921935d3.png">

In the default case it's this code which is creating garbage

[GroupObserver.cs](https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/GroupObserver.cs#L79-L81
)


Hopefully @JuDelCo is right and this changes in the future
