### ISSUE TITLE
[Suggestion] Strong typing in public API

### ISSUE THREAD

**Issue by srivello** [sschmid/Entitas-CSharp#143]
I have a suggestion for more strong typing in the public API of Entitas. As a developer using the system, the strong typing would reduce (casting) code on my side. 

Reasons for the current lack of strong typing may include some run-time optimizations. If so, I'd prefer a fast system instead of my request :)

Ex. We currently see this behavior

`System iSystem = Pools.pool.CreateSystem<VelocitySystem>() as VelocitySystem;  `

Ex. What I suggest instead is strong typing when CreateSystem<T> is called. (The following does not compile without manually adding some casting code).

`VelocitySystem velocitySystem = Pools.pool.CreateSystem<VelocitySystem>();`

Thoughts?

**Comment by sschmid** [comment]
pool.CreateSystem<T>() is a convenience method and currently returns ISystem because in case T is IReactiveSystem this method actually returns a new instance of ReactiveSystem with T being the subsystem. This means a general casting to T wouldn't work.

Additional thoughts:
I was thinking to add pool.CreateReactiveSystem(), this way your suggestion would work. 2nd thought was to remove CreateSystem<T> altogether and just provide CreateSystem(ISystem system) the reason being increased build size when compiling AOT, e.g. iOS.

Even more thoughts and a glimps into the future of Entitas:
I added pool.CreateSystem() mainly inject the pool if needed and wrap a system into a ReactiveSystem if needed. When I'd add pool.CreateReactiveSystem() there would be only one reason left for this method (ISetPool).

I plan to get rid of the static Pools class and make it a normal class where you can set multiple pools yourself. Instead of passing a pool to ISetPool we could pass in the pools instance and have sth like
```csharp
pools.core
pools.meta
```

Then I'm wondering if we can get rid of the ISetPool interface altogether and just pass the pools instance as a constructor parameter if needed.
