### ISSUE TITLE
Tweening In Entitas

### ISSUE THREAD

**Issue by srivello** [sschmid/Entitas-CSharp#145]
In my EntitasCoverShooter project I tween position of some Entities. NOTE: This project is still incomplete as of August 13, 2016.

When I process the entities which have a `PositionComponent`, I check a custom useTween property. The result is good. Entities can tween or not tween the position and the system respects it. This solution was inspired by another Entitas sample project. I forget which one :) For now, I do all tweens at the same duration of `0.3f,` but of course that could be stored in the component too.

As a side note, outside the scope of this post...
 * I use the 3rdParty [HOTween](http://hotween.demigiant.com/). I like it :)
 * I use `UnityEngineReplacementUtility` as an an experimental approach to include NO `UnityEngine` namespace types in my Entitas `Components` and `Systems`. Its working well so far. I mention it since its included in the snippet below, but not to generate discussion on it.
 * My personal approach to Entias is to store data in `Components`, the process data in `Systems`, and to update `GameObjects` only in `Controllers`. The example below follows that convention.

In the [ViewController.cs](https://github.com/RivelloMultimediaConsulting/EntitasCoverShooter/blob/55100ff54eb8de7aabe3deb2565be273145074dd/unity/Assets/RMC/Common/Scripts/Runtime/Entitas/Controllers/Singletons/ViewController.cs) I do this;

```
if (!entity.position.useTween)
{
    ((GameObject)entity.view.gameObject).transform.position = UnityEngineReplacementUtility.Convert(entity.position.position);
        
}
else
{
    ((GameObject)entity.view.gameObject).transform.DOMove(UnityEngineReplacementUtility.Convert(entity.position.position), 0.3f);
}
```

Questions
 1. What alternative approaches can there be to handle games with entities that sometimes tween and sometimes do not tween?

**Comment by sschmid** [comment]
I usually differentiate between two types of tweening: relevant and irrelevant tweening (couldn't come up with  better name for now :)).
Relevant meaning that an actual system needs to take care of tweening component values like position. This means you have to write your own tweening system and that the actual position change is important to the simulation.
Irrelevant meaning that the tween is purely view related and animates a state change, e.g Match-One example. A piece falls down 3 cells in the grid and the position is set to the final value immediately but the view is animated over time using [DOTween](http://dotween.demigiant.com) (if you like HOTween you'll love DOTween)
[RenderPositionSystem.cs](https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Features/RenderPosition/RenderPositionSystem.cs#L15)

But if we'd had a sophisticated TweenSystem for Entitas already, we could basically use it for everything. This is an idea that @mzaks had for a while.

**Comment by JuDelCo** [comment]
Besides tweening, i have been around the question for a couple of days. ¿Where or how is supposed to store those small variables used for timing (ex: 2 sec doing something, that timer) or internal state? Not in systems but i think in components neither because then there will be so many components or variables inside components (ex: to do a value transition over time, i need 5 variables: a start time, a timer counter, a start value, a end value and current value, but all of this is related to some component).

How should approach those cases? I'm still trying to find a good solution to this.

Can @mzaks show a bit more about his idea?

**Comment by aqaddoumi** [comment]
Hello, I’m thinking of building a TweenSystem for Entitas. I have some ideas of how to implement it, I’ve been looking at HOTween, GoKit and iTween. They have some similar approaches to tweening and some differences.

I’m thinking of creating a TweenClass, store it in a Component that you add to entities and have a TweenSystem that act on the variables of that class (Delay, TweenType, Tick, Done, etc..) and make the necessary changes for that entity. 

You would also have other required components (Position, Rotation, Scale and Color) to be in the tweening entities so that the TweenSystem can make the changes to those component and you would create any Reactive system that act on those changes as you like. So the TweenSystem is only responsible for changing those components and not what happens afterwards.

There will be a static class or namespace that you can access from other systems so they can change or invoke the TweenComoponent for specific entities by writing for example.

Tweener.Position(e, 0.5f, new Vector(1,1,1));

So you pass the entity and the parameters and the Tweener static MonoBehaviour would change the TweenComponent for that specific Entity.

So if you would build something like this how would you go about it? and what do you think is wrong with this approach or what problems would I encounter? Also is there a better approach for this?

Also I haven’t figured out how I would make Tween Sequences yet or that syntax for the sequencing. If you have any ideas about that, please do share :)

**Comment by kicholen** [comment]
I think I'v [implemented](https://github.com/kicholen/SpaceShooter/blob/master/Assets/Source/Src/System/Tween/TweenSystem.cs) sth similar to your idea of TweenClass it's not great, syntax could be much smaller but it gets the job done. The idea was taken from [universalTweenEngine](http://www.aurelienribon.com/blog/projects/universal-tween-engine/), it would be easy to modify accessors in a way that ReacitveSystems would work as well. 
`e.AddTween(true, new List<Tween>());
            e.tween.AddTween(e.position, EaseTypes.quadIn, PositionAccessorType.X, timeLimit)
                .From(e.position.pos.x + offset)
                .To(e.position.pos.x)`

**Comment by mzaks** [comment]
@aqaddoumi I would add `AnimationStateComponent` which value captures the `enum AnimationState {Waiting, Running, Done}`
Than have another component:
```csharp
public class StartAnimatingWhenDoneComponent : Component {
  public Set<Entity> allOf;
  public Set<Entity> anyOf;
  public Set<Entity> noneOf;
}
```
You could also add similar components: `StartAnimatingWhenRunningComponent`, `StartAnimatingWhenWaitingComponent`.
Than have a reactive system `ScheduleAnimationSequenceSystem` which will listen to `AnimationStateComponent` iterate over all entities which have `StartAnimatingWhenRunningComponent` , `StartAnimatingWhenWaitingComponent` and  `StartAnimatingWhenDoneComponent` and than decide if they should switch from `Waiting` to `Running`

Basically what I suggest is a dependency tree. Sequence A -> B -> C. Means that B is scheduled when A is done, and C is scheduled when B is done. With `allOf`, `anyOf`, `noneOf` semantics you can map any kind of wild constellations. I think it might even be a bit over the top. I personally would start with just `allOf` but hey here it is just a concept :).

What I would also love to see is that user can decide if the animation is based on delta time or tick. Also if it is delta time it would be good if it would be captured by `DeltaTimeComponent`. The reasoning about it is following. If it doesn't take unity delta time but it's own delta time, user can implement custom pausing which will also stop animations.

One more random thought. As @JuDelCo mentioned Tweening system implies lot's of components. It might make sense to have a special pool for them.

**Comment by aqaddoumi** [comment]
@kicholen Thanks for your example, yes it gets the job done, I've implemented a tweening system in my previous project but it was very hacky, that's why I'm trying to develop a more elegant system that I can use for my next project/s and share with the entitas community.

I don't want to go off rail but the way you handled Entitas in your project seems very different from the way I've used it or from other examples on GitHub. What I'm trying to say it's very Object Oriented and less ECS. Some of your components have methods, aren't components supposed to have only data and let the systems handle the logic? I still need to go through your example more thoroughly but what we're you trying to solve by this and why did you use and MVC. PS you can be very brief :)

@mzaks what I actually meant by having a TweenClass is actually two classes, one small class called for example TweenClass that have the tween properties and another, let's call it TweenerClass that holds multiple Tweens in a list in it. It also hold the AnimiationState and other and other necessary variable and methods for adding, modifying and running the tweens. What advantages would I get by using another AnimationStateComponent and System than having all of those saved in the TweenerClass that's saved in a component and have the TweenSystem iterate through them?

Also the DeltaTimeComponet was how I was planning to implement it :)

You guys and the entitas community are awesome and very helpful.

**Comment by mzaks** [comment]
I would say it is a question of flexibility. By providing abstractions and hiding the state you can implement a very clean way of using the system. However it will push user into certain way of solving the problem. By exposing the state as components you can enable things like complex animation morphing. The developer who knows the animation of the game can write custom systems which can evaluate current animation state and decide how to proceed.

**Comment by aqaddoumi** [comment]
Okay, thanks for the answer, I will see how I will go about it and keep you guys updated :)
