### ISSUE TITLE
Unsubscribing Entitas Events

### ISSUE THREAD

**Issue by srivello** [sschmid/Entitas-CSharp#146]
In my Entitas projects I regularly subscribe to events within the `Initialize` method of `System` classes.

Ex. 
```
public void Initialize()         
{
     _pool.GetGroup(Matcher.AllOf(Matcher.Score)).OnEntityAdded += OnGameEntityAdded;         
}
```

Questions
 1. I assume I should follow best practices and manually unsubscribe (-=) for every subscription (+=), yes?
 1. If yes, within what scope (method & class) should I do the unsubscribe?

**Comment by sschmid** [comment]
Before I get started: Initialize is the perfect place to subscribe to events since it will work great if you ever need to soft-reload you game (see #82). So well done ;)
If you use pool.Reset() it will also do the unsubscribing in groups for you. But you are right, being a good citizen means cleaning up after yourself. This is exactly why I've planned to add sth like 'ICleanupSystem' or 'IDeinitializeSystem' (not sure about the name yet) to have a proper place to do so. So we can call
```csharp
systems.Initialize();
systems.Execute();
systems.Deinitialize();
```

**Comment by sschmid** [comment]
Btw, I'm not quite sure what your current design is, but consider preferring ReactiveSystems over group events if possible (and if it makes sense of course). I generally try to use GroupObservers only if I really need to.

**Comment by sschmid** [comment]
Btw, I added ICleanupSystem and IDeinitializeSystem. They will be in the next release.
The suggested order is
Initialize

Execute
Cleanup

Deinitialize

**Comment by sschmid** [comment]
More info about Cleanup:
I often end up having a global cleanup system in the end which is removing flags or flagging entities to destroy. Instead of having one systm that basically know about all features you can now simply implement ICleanupSystem to  remove component (or other cleanup) in the same system where you actually add those components
