### ISSUE TITLE
Why close pull requests and recreate the commits instead of merging?

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#16]
I just watched your presentation and what you guys have built seems extremely impressive. One project related question I had is why are you closing pull requests and recreating the commits instead of merging them directly in from contributors? 

Few examples:

* https://github.com/sschmid/Entitas-CSharp/pull/2
* https://github.com/sschmid/Entitas-CSharp/pull/1

I don't want to be to be too critical of your workflow if it works for you but it seems like this approach has a few drawbacks:

1. It makes this project look less active then it is because the contributor count remains at 1 instead of reflecting the accurate # of contributors.
2. It doesn't give people proper credit in the git commit history.
3. It makes thing harder to track, because an unaccepted PR looks the same as an accepted PR.

There was a post about this on the [programmer stack exchange](http://programmers.stackexchange.com/questions/160086/should-a-github-maintainer-rewrite-authors-in-pull-requests) that covered some alternative ways to avoid merge commits (assuming that is what you are avoiding).

Again, I don't want to over step my bounds, this is an attempt at some constructive cristism. Please ignore if I am misunderstanding something about the project or your workflow.

**Comment by sschmid** [comment]
Hi, your points are valid and I'm happy to merge pull request! In fact, I encourage you guys to do so, since it helps making Entitas better. But you are right, looking at the current state of the pull requests you might get a wrong impression.
Here's an attempt to explain what happend:
The two example pull requests you were referencing are both from co-wokers. In the case of #1, we were discussing and sketching out the changes together and after he made a pull request I implemented it again in a test driven manner, because all features in Entitas are added with writing tests first.
#11 for example was just one line, so I quickly tested it on Mac and Windows and yeah, then it was already in. I could have removed it again and merge the pull request, but I didn't :) But I mentioned @movrajr in the release notes to give him credit.

Hope that answers your question and again: I'm happy to merge pull request!

**Comment by JamesMcMahon** [comment]
Ah, sorry for the misunderstanding. Thank you for your reply!
