### ISSUE TITLE
CodeGenerator generated folder adds unnecessary "Generated/" suffix

### ISSUE THREAD

**Issue by chrischu** [sschmid/Entitas-CSharp#19]
If one changes the generated folder setting in the properties to a folder that does not end with "Generated/", that suffix is added.

I think that is unnecessary. For example when I only want to have one folder with all generated code, but I want to distinguish between the files generated by Entitas and by other frameworks/own code by putting them in different folders (e.g. "Assets/Generated/Entitas" for entitas and "Assets/Generated/OtherFramework" for another framework).

This is currently not possible (at least not without an necessary folder level ("Assets/Generated/Entitas/Generated").

**Comment by sschmid** [comment]
True, that's currently not possible atm. The initial motivation behind this decision was safety and protection against file loss, because when you hit the generate button, it also clears (deletes) the generated folder. If for some reason you specify a wrong folder, you end up deleting this folder. But I'll think about it again... ;)

**Comment by chrischu** [comment]
Mhh just a quick idea: Maybe you should implement some kind of safeguard (like a yes/no dialog) before the folder is deleted when it looks like it is not a folder just containing Entitas files?
