### ISSUE TITLE
Swapping components between entities causes component to return to pool

### ISSUE THREAD

**Issue by LeRondPoint** [sschmid/Entitas-CSharp#213]
Given the following code :

```
Entity leftGapEntity = levelGaps.GetEntities()
                         .FirstOrDefault(e => e.gap.LeftPlatform == platform);
Entity rightGapEntity = levelGaps.GetEntities()
                         .FirstOrDefault(e => e.gap.RightPlatform == platform);
GapComponent leftGap = leftGapEntity.gap;
GapComponent rightGap = rightGapEntity.gap;

leftGapEntity.ReplaceComponent(GameplayComponent.Ids, rightGap);
rightGapEntity.ReplaceComponent(GameplayComponent.Ids, leftGap);
```

One of the swapped components (rightGap in this case if I'm not mistaken) get returned to the pool and then reused, causing side effects.

I'm using the following as a workaround but I would have expected to be able to swap components between entities.

```
leftGapEntity.ReplaceGap(rightGap.Width, rightGap.LeftPlatform, rightGap.RightPlatform);
rightGapEntity.ReplaceGap(leftGap.Width, leftGap.LeftPlatform, leftGap.RightPlatform);
```

**Comment by sschmid** [comment]
Yes, that's right. You have to use `entity.ReplaceGap()`. Components are object pooled under the hood to reduce memory allocations. So currently, your workaround is the correct way of doing it.
This issue could be solved by having a reference count to components, same as there is a reference count for entities (retain / release).
I would have to see, if that will have a negative effect on performance. Otherwise, the only thing I can say right now is to use the generated methods instead of manually calling `entity.ReplaceComponent()`. Rule of thumb: if you're using ComponentIds anywhere in your code, consider this as using internal api. Consider this as an internal implementation detail that can change at any time. It might not change, but try using matchers and generated methods instead. Entitas also works completely without the generated methods, but then you have to be aware of more details like the issue you just described.

**Comment by LeRondPoint** [comment]
ok, then why is it public?  From what I can see it's only public for a unit test... it would be easy to fix that and most likely the add and remove variants as well.
