### ISSUE TITLE
New to Entitas

### ISSUE THREAD

**Issue by Ziboo** [sschmid/Entitas-CSharp#225]
Hi everyone,

 I'm trying to get my head around Entitas, more specificly ECS, I'm really new to that.

I was wondering how you would implement a simple mecanic:
- A Button
- A Door

When you click the button it opens the door. The level could have multiple buttons and multiple doors.
I don't really know where to start, but when planning it inside my head, and by looking at samples, there is something that I can not think where it should be implemented and when.

How do the button can reference the door ?

Do I need to create a monobehavior for that ? can it be done at design time (in editor) ?

Sorry for the dump question, it's very hard to think ECS when you have done OOP all your life

Thanks a lot

**Comment by e-gs** [comment]
Hi,

I'm new to the whole ecs thing as well - anyhow I'd approach that task as follows:

We need to store the state of the doors, so we should have a door-pool.
The door entities need three components:
-  Id: integer or string so we can address the door
-  DoorState: boolean to indicate whether the door is opened or closed
-  View: a reference to a Monobehaviour that represents the door in the scene 

Since we want to change the state of the doors we need some type of input.
Let's collect the Inputs in an input-pool. Since the Input-Entities only need to tell us which door to change they will merely need one component:
- Door-Id: int/string telling us which door to open/close

Now we use a ReactiveSystem that is triggered whenever an Input-Entity is created. The System will then search the Door-Pool for an entity with the given Id (plenty of room for optimization here), change its DoorState and update the view. 

Finally we need two MonoBheaviours a ButtonInputController that creates an Input-Entity when a Button is pressed and a DoorView that displays the DoorState.

You could initialize the door-pool from the views OnStart. Every DoorView creates a door-entity and adds the necessary components.

I hope that makes sense...

Cheers

**Comment by Ziboo** [comment]
Thanks for your detailed answer.

That's actually kind of what I had in mind, but man, that's a lot of code for doing just a simple thing. Just getting my had around ECS it hard.

I was wondering if Entity or Component instances have a unique ID already built in ?

Thanks

**Comment by bddckr** [comment]
If you want a unique ID for *every* entity you could add a simple `IDComponent` to every one and give it a new GUID for example.
Make sure to have a look at `EntityIndex`/`PrimaryEntityIndex`. Either use it with your ID stuff or think about how existing components could be utilized to provide an `EntityIndex`.

**Comment by Ziboo** [comment]
Thanks for your answer :)
