### ISSUE TITLE
How to know if entity is added or removed in reactive system

### ISSUE THREAD

**Issue by Zammy** [sschmid/Entitas-CSharp#242]
```
using Entitas;
using System.Collections.Generic;

public class PlayerSelectionCageSystem : ISetPool, IReactiveSystem
{
    Pool _pool;

    public void SetPool(Pool pool)
    {
        _pool = pool;
    }

    public TriggerOnEvent trigger
    {
        get
        {
            return Matcher.Player.OnEntityAddedOrRemoved();
        }
    }

    public void Execute(List<Entity> entities)
    {
        
    }
}
```

How do I know if entity is added or removed ?

**Comment by vladpazych** [comment]
You can check `if (entity.isPlayer)` inside of Execute method.

**Comment by Zammy** [comment]
I do not understand how this will help me. They are supposed to have player component because of the trigger. Also... how does this tells me if it is added or removed.

**Comment by Roms6** [comment]
They're not supposed to hold a Player component, because this system is reacting when it's added or removed. The entities you'll be iterating in the `Execute(List<Entity> entities)` method actually include entities having your Player component (because it has just been added), **and** entities not having this component (because it has just been removed). This is why you should check `if (entity.isPlayer)`, to know something has been selected or deselected.

**Comment by sschmid** [comment]
@Zammy Did the answer help you? If so feel free to close the issue, if not add another comment if you need further help.
