### ISSUE TITLE
CleanupJustBeforeExecute systems

### ISSUE THREAD

**Issue by beck-daniel** [sschmid/Entitas-CSharp#243]
One constant pain point of ECS architectures is that the order of systems matters. In Entitas in particular, due to the very basic Initialize, Execute, Cleanup  order of things I sometimes find myself implementing a CleanupBeforeExecute system. Such a system cleans events just before execution , letting all other systems the opportunity to consume these events, not only systems that were created after the CleanupBeforeExecute system.

I realize that this can be solved by splitting the system into two smaller ones, or by using a pub/sub system using callbacks. But I don't think this is reasonable. 

How do you guys feel about adding such a system type to Entitas?

**Comment by sschmid** [comment]
Can you give a simple example? I'm not quite sure if I understand you correctly.

**Comment by MoritzVossKing** [comment]
I think order of systems is a pro, not a con, of ECS systems, and in particular, Entitas (as opposed to event driven models, etc.)

You can have (but admittedly also sometimes need to manage) that temporal dependency, which in a pure event driven system you'd always need to fully micromanage (usually with chains of events, or order of handlers).

**Comment by danielbe1** [comment]
Well, say that I have an `Enemies` system that handles `Enemy` components, it is responsible of creating and destroying them.
And say that my execution code looks something like this:
```
void Update {
  _systems.Execute();
 _systems.Clean();
}
```

Now, say that I have a system that wants to create an enemy, and waits until that enemy is destroyed.
This will obviously not work, since if the system is created before the `Enemy` system then it will not be able to handle destroyed `Enemy` components and if it is created after the Enemy system then it will not be able to create enemies.

So yeah, I could split one of the systems, but that seems unreasonable as this is a very trivial use case.

**Comment by MoritzVossKing** [comment]
Isn't that a use case for ICleanupSystem?

**Comment by danielbe1** [comment]
> Isn't that a use case for ICleanupSystem?

Not if the entities are destroyed.
