### ISSUE TITLE
Entitas.dll binary

### ISSUE THREAD

**Issue by T2RKUS** [sschmid/Entitas-CSharp#244]
On each release of Entitas can we have pre-compiled separated dll's of the framework, Entitas.dll (pure c# code), Entitas.Unity.dll (Entitas monobehaviour code that doesn't contain editor code such as custom inspectors, drawing functions etc for visuals), Entitas.Unity.Editor.dll (for editor related code, custom inspectors, drawers, color functions, visuals etc).

As an alternative to the source code if we want to have a cleaner project and don't want any third party assets / code to be visible but our own?

**Comment by sschmid** [comment]
Currently you have to use the source code of the at least the core of Entitas, since it contains partial classes.
But just this week I started testing working around this. Based on the latest develop I picked up the type-safety feature again which might enable me to deploy Entitas as a dll. I'll look further into this after the xmas holidays.

**Comment by sschmid** [comment]
Hey, fyi,
with the current state of develop you should be able to compile Entitas to .dll.
Code Generation doesn't rely on partial classes from the lib anymore

**Comment by sschmid** [comment]
As a part of restructuring Entitas and managing dlls and dependecies, this is the current project structure

<img width="372" alt="entitas-structure" src="https://cloud.githubusercontent.com/assets/233700/24585770/8f205c3e-1792-11e7-9da2-d04470f71737.png">
