### ISSUE TITLE
Using Entitas in a shared library

### ISSUE THREAD

**Issue by awalltoo** [sschmid/Entitas-CSharp#247]
I'd like to use Entitas in a library shared between multiple projects.  As an example, say my game is structured like so:

- Server (standalone executable, uses Entitas-C#)
- Client (Unity project, uses Entitas-Unity)
- Common (shared library used by both server and client)

If I include Entitas in my common project, then I can't import the common library into either my server or client projects because I get conflicts between the common library's version of Entitas and the server/client's version.  For any other library, the workaround would be to build that library as a separate project and reference the resulting .dll from all three of the above projects.  But since Entitas's code generation relies on partial classes, I actually need to include the source in every project that makes use of it.

Do you have any suggestions for how I could structure a game like this and use Entitas in each of the projects?  Thanks for your help!

**Comment by sschmid** [comment]
I had a similar issue with the Entitas project itself which has a Tests project (and others). Referencing the Entitas project in the Tests project which also contains generated code doesn't work for the the reason you explained with partial classes. I ended up adding the existing Entitas folder as a link instead of referencing the project or copying the sources. This solved the issue for me. Hope that helps.

Btw, coincidentally I just finished a draft version of Entitas today which enables me to distribute Entitas as a dll. In the future you're not required to import the sources anymore and the code generator doesn't extend existing class from the Entitas library. Good times ahead :)

**Comment by sschmid** [comment]
see #244

**Comment by awalltoo** [comment]
Oh cool, definitely looking forward to that then!

I'm not sure how well Unity deals with source files that are outside the project directory, so I don't know if the first solution would work for me.  But if the dll version is coming, I can work around it for the time being.  Thanks!

**Comment by JuDelCo** [comment]
Looking forward for that update/dll ! I want to start another project with entitas, so migration will not be a problem for me

**Comment by T2RKUS** [comment]
I'm just waiting on the new version before I start with my game. I intend to use a Dependency Injection library with Unity so I'll see how well Entitas and DI mesh.

**Comment by sschmid** [comment]
@T2RKUS IMO, you don't need an DI framework when working with Entitas. If you have a ref to the pool you basically have access to everything.

**Comment by sschmid** [comment]
Hey, fyi,
with the current state of develop you should be able to compile Entitas to .dll.
Code Generation doesn't rely on partial classes from the lib anymore

**Comment by WoLfulus** [comment]
THANK GOD! <3

**Comment by T2RKUS** [comment]
@WoLfulus If you're thanking "god" and Simon made Entitas by "god" do you mean Simon? :D
