### ISSUE TITLE
GroupEventType.OnEntityRemoved used in IReactiveSystem

### ISSUE THREAD

**Issue by jraselin** [sschmid/Entitas-CSharp#25]
Hi,

When ```GroupEventType.OnEntityRemoved``` is used with ```IReactiveSystem```, ```List<Entity> entities``` parameter on method ```public void Execute(List<Entity> entities)``` doesn't correspond to the removed entities (seems to match random entities within the pool)

It would be useful to get the removed components 

Regards

**Comment by JuDelCo** [comment]
The real problem is destroyed entities (not just his components) will be reused to create another entity. It works like any component or entity instantiated will be used as a cache object to "instantiate" new ones if they are "destroyed".

GroupObservers (and by extension, ReactiveSystems...) WILL NOT notice this, they just think the entity not match his requirements so they keep anyways a reference of them (if they matched before)

That's why in the examples provided in sschmid acount (the match-one and the cars one) they built a "DestroySystem" which executes at the very end of the loop, destroying in that moment any entity with the component "DestroyComponent".

**Comment by jraselin** [comment]
Thanks for your explanation.

For now, I won't use ```GroupEventType.OnEntityRemoved``` but only ```GroupEventType.OnEntityAdded```.

Regards

**Comment by sschmid** [comment]
Next release 0.22.0 will solve this issue.
