### ISSUE TITLE
Entitas goes type-safe

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#257]
# Problem

### Example 1

Given:
- HealthComponent in [Game] context
- LevelUnlockedComponent in [GameState] context

Expected:
```csharp
var e = gameContext.CreateEntity();
e.AddHealth(42); // Works
e.isLevelUnlocked = true; // Doesn't work, because LevelUnlocked in in different context
```

Unfortunately, you currently can write the code above but you will most likely get a runtime exception.
This doesn't scale well if your components count and context increases.

### Example 2

Given:
ReactiveSystem that acts on [Game] context

```csharp
public sealed class HealthSystem : ReactiveSystem {

    // This system works on contexts.game
    public HealthSystem(Contexts contexts) : base(contexts.game) { }

    protected override Collector GetTrigger(Context context) {
        // Wrong matcher should result in compiler error
        // Only accept GameMatcher
        return context.CreateCollector(GameStateMatcher.LevelUnlocked);
    }

    protected override bool Filter(Entity entity) {
        // Wrong api for GameEntity
        // Only accept GameEntity
        return entity.isLevelUnlocked;
    }

    protected override void Execute(List<GameEntity> entities) {
        // Only pass in GameEntity which has auto completion for [Game] context only
    }
}
```

# Solution
Add generic
- `Context<TEntity>`
- `ReactiveSystem<TEntity>`
- `Group<TEntity>`
- `Collector<Entity>`
- etc...

and update the code generator to generate

- `IHealthComponent`
- `GameEntity : IEntity`
- Extend Context
- etc...

**Comment by vedun-z** [comment]
Hi! We are starting to develop our game and looking around for good frameworks. We've watched your videos in youtube and we really love your approach. But it seems like Entitas in the middle of breaking changes. Entitas really needs type-safety because a partial class that includes all possible fields looks really ugly. However literally every release breaks backward compatibly with previous one.  Are you going to create "stable" with long term support? At least, do you have any estimation of type-safety release?
