### ISSUE TITLE
ReactiveSystem - GetTrigger & Filter

### ISSUE THREAD

**Issue by NemoStein** [sschmid/Entitas-CSharp#264]
Is it really necessary to have this kind of filtering?

```c#
protected override Collector GetTrigger(Context context)
{
	return context.CreateCollector(TestContextMatcher.TestComponent);
}

protected override bool Filter(Entity entity)
{
	return entity.hasTestComponent;
}
```

The Collector is triggered only if a TestEntity is added to TestContext, so, this filter is completely useless, isn't?

Also, I saw some places with more than one filter, like:
```c#
protected override bool Filter(Entity entity)
{
	return entity.hasTestComponent && entity.hasAnotherComponent;
}
```
Isn't this also useless if I build my trigger with `Matcher.allOf(TestContextMatcher.TestComponent, TestContextMatcher.AnotherComponent)`?

Furthermore, #257 states that:
> // Wrong api for GameEntity
> // Only accept GameEntity

Meaning that the filter should be more strict in what it accepts, leading me to think that it's even less useful when you don't need to check specific values in components (instead of just checking if the entity has some component).

**Comment by sschmid** [comment]
@NemoStein That's a very good question and will definitely make it into the faq :)

The trigger should really only be used as a trigger. Neither does it ensure nor exclude and entities with specific components. In the past, people used the trigger to sth like you wrote `Matcher.allOf(TestContextMatcher.TestComponent, TestContextMatcher.AnotherComponent)`

While this works, it is not good practise. In most of the cases a trigger should only be exact one matcher. You should use it in combination with the filter to ensure or exclude entities.

If you trigger for component A it doesn't necessarily that the entities still have that component once you execute.

Rule of thumb:
every component that you read or write to in the execute (has, get, add, replace, remove) method has to be in the filter. The filter is not optional anymore to enforce good practise. This fits also really well with our vision with the DSL, where the systems are generated for you, so you don't have to implement triggers and filters anymore because we can infer that from the DSL and will automatically generate that for you. The DSL will follow the rules mentioned above, meaning every access to a component will automatically be ensured.

**Comment by sschmid** [comment]
Checking for components with `e.hasXyz` doesn't really have a bad impact on performance, but will greatly improve avoiding certain kind of bugs.

**Comment by NemoStein** [comment]
> If you trigger for component A it doesn't necessarily that the entities still have that component once you execute.

Does it mean that the `GetTrigger` is triggered before systems loop starts (in the beginning of the game loop) and `Filter` is called just before `Execute`?

I mean, is it possible that, before anything get processed by the systems queue, an entity component triggers some system trigger but, before reaching that system, the component could be removed by another system earlier in the queue?

**Comment by sschmid** [comment]
@NemoStein Based on the trigger entities will be aggregated by the system immediately when ever and where ever the change to the entity happened. This means at a later point of time where you actually execute the system other logic might have removed the component again.

Imo, the issues are a good place for me to talk about any feedback, questions or suggestions. I will be notified via mail, can manage them and can link them to actual code changes and PR. Atm, I can't see myself also moderating a forum.

**Comment by NemoStein** [comment]
Thank you for your time to explain... I think that I understand the workflow far better now. =]
