### ISSUE TITLE
Getting Started 

### ISSUE THREAD

**Issue by Crioca** [sschmid/Entitas-CSharp#283]
Hi,

I've run into some issues while installing Entitas for Unity, not sure if this a bug or user error.

I created a fresh project and extracted the contents of Entitas-Unity.zip into the project's assets folder, but the Entitas tab is not appearing and there's a number of compile errors in my console.

I've attached a screenshot of my Unity window and the assets folder. 
![entitasss](https://cloud.githubusercontent.com/assets/7008622/22861037/c61a6168-f162-11e6-9f65-36ba98702410.png)
Any help is appreciated, thanks.

**Comment by KumoKairo** [comment]
Take a look at the console - it has a JS error. Unity thinks that .js files are Unity Scripts and tries to compile that. It fails because there's some _real_ javascript code involving jQuery and things. Delete everything except Entitas folder from your project (so your Project tab displays only one thing - the folder named "Entitas"). It should then compile ok

**Comment by Crioca** [comment]
Thanks, that did the trick.

**Comment by KumoKairo** [comment]
To be more explicit here.

1. Delete EVERYTHING
2. Create a folder named "Libs" inside of your project
3. Open Entitas-Unity ZIP archive
![image](https://cloud.githubusercontent.com/assets/2943071/22861084/0540e728-f121-11e6-9104-2567df12bee0.png)
4. Copy "Entitas" and "Plugins" folders inside of your newly created LIBS folder
5. Done

This will not work if you'll just drop Entitas and Plugins folder into your project because of the way Unity handles folder names

**Comment by Crioca** [comment]
So just deleting everything except the Entitas folder seemed to work, but I'll follow those steps to be safe.

**Comment by sschmid** [comment]
The Documentation folder should not be part of your Unity project. It contains the docs and no source files. That's why you got errors.

**Comment by KumoKairo** [comment]
@sschmid it will be a common error to copy the Plugins folder inside of the root Unity "Assets" folder, also leading to errors. Please consider renaming the folder to something more Unity-safe (so it's harder to screw things up when importing Entitas to Unity)

**Comment by dzliergaard** [comment]
Note: "Plugins" is now called "AddOns."
