### ISSUE TITLE
[Entitas:] Support for multiple contexts in ReactiveSystem

### ISSUE THREAD

**Issue by szagi** [sschmid/Entitas-CSharp#303]
Hi!

We're currently developing game in Entitas and loving it very much :) Hope we use it in our next projects :)

Recently I came up one two problems during updating process to new version 0.37.0 from 0.36.0:

1. We have reactive system DestroySystem which can operate on several contexts (tile, core, meta),  but have different collectors and I tried to use Entity type for this system and use correct collector for each entity like this:

```
protected override Collector<Entity> GetTrigger( IContext<Entity> context ) {
            if ( context is CoreContext ) {
                return (Collector<Entity>)Contexts.sharedInstance.core.CreateCollector( CoreMatcher.Destroy, GroupEvent.Added );
            } else if ( context is TilesContext ) {
                return Contexts.sharedInstance.tiles.CreateCollector( TilesMatcher.Destroy, GroupEvent.Added );
            }else if(context is MetaContext){
                return Contexts.sharedInstance.meta.CreateCollector( MetaMatcher.Destroy, GroupEvent.Added );
            }
        }
```

but I can't cast specific Collector (Collector<CoreEnity>, Collector<TilesEnity>, Collector<MetaEnity>) to Collector<Entitas.Entity> is there any method to do this? Or I need to create DestroySystem for each entity? 

And 2.

In one of our system we have Collector, which operates on two contexts: 

```       
 public static Collector<Entity> GetCollector( Contexts contexts )
        {
            return new Collector<Entity>( new Group<Entity>[] {
                contexts.core.GetGroup ( Matcher<CoreEntity>.AllOf ( CoreMatcher.Player, CoreMatcher.Position ) ),
                contexts.tiles.GetGroup ( TilesMatcher.TilesetConstraint )
            },
               new GroupEvent[] { GroupEvent.Added, GroupEvent.Added } );
        }
```

And there I have no idea how can I update to new version using type safety? Any tips?
  
Thanks.

**Comment by bddckr** [comment]
For the destroy systems I went with [this solution](https://gist.github.com/bddckr/3efd4fba70c4d713a0b92d77893114a2).

This only works as long as you don't need to access a component in multiple contexts. See [this gist](https://gist.github.com/bddckr/4e5035998618e39040909be1f0e9c55d) for a solution to that use case.

**Comment by sschmid** [comment]
This is actually a task I want to tackle for the next release.
Short answer: Currently a reactive system is limited to one context.

What I will try for the next release is to change the generator to generate `IGameEntity` interface instead of a class. This way we can compose custom types like
```cs
public interface MyCustomEntity : IGameEntity, IGameStateEntity, IInputEntity { }
```

which can be used

```csharp
return new Collector<MyCustomEntity>...
```

Haven't thought it through yet and cannot guarantee that it is actually possible. But I'll give it a try. On e thing that could be a problem while attempting to solve this with interfaces is the generic type constraint atm `where TEntity : class, IEntity, new()`. Interfaces don't fulfill this requirement. But I'll see what I can do.
