### ISSUE TITLE
Decouple Entitas Visual Debugging from Code Generator

### ISSUE THREAD

**Issue by T2RKUS** [sschmid/Entitas-CSharp#312]
Currently, the entitas visual debugger is coupled to the code generator because Entitas Stats is placed within the addon and uses the HideInBlueprintsInspector (which was taken out so that isn't a problem). Doesn't it make more sense to put Entitas Stats with the code generator? This problem is easily fixed by hand but I just thought it should be official. It's an unnecessary coupling.

**Comment by sschmid** [comment]
HideInBlueprintsInspector has been removed in 0.38.0.
VisualDebugging currently depends on the Code Generator Addon because it's using
`CodeGeneratorConfig` and `ContextsComponentDataProvider`

https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.Unity.VisualDebugging/Assets/Entitas.Unity.VisualDebugging/Editor/EntitasStats.cs#L40-L56

EntitasStats cannot be moved to the Code Generator Addon because it uses `Feature`
https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.Unity.VisualDebugging/Assets/Entitas.Unity.VisualDebugging/Editor/EntitasStats.cs#L63

**Comment by T2RKUS** [comment]
"VisualDebugging currently depends on the Code Generator Addon because it's using
CodeGeneratorConfig and ContextsComponentDataProvider"
which are both used in EntitasStats only? So you're saying they're coupled for the sake of knowing how many components you have in a context etc. :'( If that's the case can't we move EntitasStats to it's own add on and create a new menu item under Entitas?

**Comment by sschmid** [comment]
0.40.0 introduced another coupling. Added `ContextObserverGenerator` to VisualDebugging which makes it even more dependent on Entitas.CodeGenerator.

**Comment by sschmid** [comment]
0.41.0 has a streamlined project structure. The coupling still remains, since the EntitasStats have to retrieve information from the CodeGeneratorConfig. Only solution would be moving EntitasStats to a separate Addon.

**Comment by sschmid** [comment]
It's been a while. But I did finally remove the dependencies to Entitas.CodeGeneration.Plugins
