### ISSUE TITLE
Optimize group update performance for component add/remove

### ISSUE THREAD

**Issue by paraboxx** [sschmid/Entitas-CSharp#321]
Context::updateGroupsComponentAddedOrRemoved() uses EntitasCache for pooling the temporary groupChangedLists. EntitasCache uses Dictionary lookup over the list type to find the correct pool. This Dictionary access is quite expensive in this hot codepath. 

Dropping the use of EntitasCache and hosting the list pool directly in the Context improves the "EntityRemoveAddComponent" test performance by 20-25% on my PC with .NET. Might be even more with Unity's Mono (Is there a way to test that, too?)

**Comment by sschmid** [comment]
Yeah, I was thinking about that too. In fact, before the EntitasCache, every class had their own static cached list. As part of refactoring I moved that code to the EntitasCache. But I guess you're right, when thinking about the performance we can save a dict lookup and even the whole object pool, because all we really need is just one cached list that we reuse

**Comment by paraboxx** [comment]
I don't think a single list will do as groupchanged callbacks might add or remove components and recurse into this handler. I think you even have a test for that case.

**Comment by sschmid** [comment]
Merged! :)
Thanks for the contribution!
