### ISSUE TITLE
Why project still 0.XX? Multiplayer and Deterministic Replay?

### ISSUE THREAD

**Issue by leopripos** [sschmid/Entitas-CSharp#354]
Hello @sschmid and others,
Why the version is still 0.XX? is there a full roadmap?

And now, i want to developing multiplayer game which implementing Deterministic Replay concept. Is Entitas good enough for it? and why?

Thanks

**Comment by sschmid** [comment]
Hi,

I recently posted sth about the roadmap in the chat:
https://gitter.im/sschmid/Entitas-CSharp?at=58cdae0efe6a638b1add8d63

I'm currently working on a roslyn code generator and @mzaks is about to release Entitas-Lang which both attempt to solve the issues you might have with code generation. I also just updated the build pipeline and the Entitas code base to be deployed as dlls.
I want to have those things in before I consider going 1.0.0 since those changes might have an effect on the public api.
Having said that:
- **Entitas is ready for production**

We used it for multiple different games in different genres over the last 3 years and there are a few games already out in the AppStore made with Entitas. Take a look at the [Wiki - #madeWithEntitas](https://github.com/sschmid/Entitas-CSharp/wiki/%23madeWithEntitas)

I used Entitas in a synchronous multiplayer game and in a deterministic game where I could replay the game just by providing inputs. It's really easy to achieve this with Entitas.

> Is Entitas good enough for it?

In my opinion Entitas it currently one of the best options to build a game with a solid architecture. I'm currently working on a game with hundreds of systems and growing complexity, but it's still a pleasure to work with, and the complexity is manageable very well. We have thousands of unit tests and the game runs very smooth.

> and why?

- It's fast and optimized
- I uses way less memory than Unity
- It uses object pools and caching by default to ensure to have almost no allocations
- Data Oriented approach, composition over inheritance
- Systems that follow the Single Responsibility Principle
- It's really easy to write Unity Tests with Entitas, which can be veeery beneficial if you want to create a deterministic game
- It has proven to scale well
- Me and the great community are happy to help if you have any questions
- It's plain fun to work with :D

**Comment by leopripos** [comment]
Hi @sschmid ,

Thanks very much for your explanation.
I will start to explore more.
(y)
