### ISSUE TITLE
Unit-testing in Entitas

### ISSUE THREAD

**Issue by nbreum15** [sschmid/Entitas-CSharp#375]
Unit-testing is not possible with the current try-catch block in the Contexts.cs because the reflection-based method call to InitializeContexObservers() throws an exception. I'll repost my comment in #362 here:

>Placing the try-catch like that still produces an exception for me. Placing it like the following works:
>```
>public partial class Contexts {
>
>    #if(!ENTITAS_DISABLE_VISUAL_DEBUGGING && UNITY_EDITOR)
>
>    [Entitas.CodeGenerator.Api.PostConstructor]
>    public void InitializeContexObservers() {
>        try {
>                CreateContextObserver(game);
>                CreateContextObserver(gameState);
>                CreateContextObserver(input);
>        } catch (System.Exception) {  }
>    }
>
>    public void CreateContextObserver(Entitas.IContext context) {   
>        if (UnityEngine.Application.isPlaying) {
>            var observer = new Entitas.Unity.VisualDebugging.ContextObserver(context);
>            UnityEngine.Object.DontDestroyOnLoad(observer.gameObject);
>        }
>    }
>    #endif
>}
>```

**Comment by sschmid** [comment]
I can't really see what the difference is. Why does moving the try catch block help?

I'd say we should find out why there is an exception in the first place, since there shouldn't be one. Is it the security exception? Are the dlls unblocked?

**Comment by nbreum15** [comment]
Unblocking does nothing. The error message i get is:
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.SecurityException: ECall methods must be packaged into a system module.
           at Contexts.CreateContextObserver(IContext context)
           at Contexts.InitializeContexObservers() in D:\GitHub\UnityProject\Assets\Generated\Contexts.cs:line 82 (this is the CreateContextObserver(input) method)
           --- End of inner exception stack trace ---
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
           at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
           at Contexts..ctor() in D:\GitHub\UnityProject\Assets\Generated\Contexts.cs:line 50

**Comment by nbreum15** [comment]
I think Unity does something very weird when they throw exceptions. Because doing the following makes the try-catch block work fine as @sschmid pointed out. 
```
public partial class Contexts {

#if(!ENTITAS_DISABLE_VISUAL_DEBUGGING && UNITY_EDITOR)

    [Entitas.CodeGeneration.Attributes.PostConstructor]
    public void InitializeContexObservers() {
        CreateContextObserver(game);
        CreateContextObserver(gamestate);
        CreateContextObserver(input);
    }

    public void CreateContextObserver(Entitas.IContext context) {
        try {
            if(IsPlaying()) {
                var observer = new Entitas.VisualDebugging.Unity.ContextObserver(context);
                DontDestroyOnLoad(observer);
            }
        } catch(System.Exception) {
        }
    }

    private bool IsPlaying()
    {
        return UnityEngine.Application.isPlaying;
    }

    private void DontDestroyOnLoad(Entitas.VisualDebugging.Unity.ContextObserver observer)
    {
        UnityEngine.Object.DontDestroyOnLoad(observer.gameObject);
    }

#endif
}

If someone can explain this mystery then I'm glad to hear it.

**Comment by nbreum15** [comment]
So basically doing the following works:
```
    public void CreateContextObserver(Entitas.IContext context) {
        try {
            UnityCode(context);
        } catch(System.Exception) {
        }
    }

    private void UnityCode(Entitas.IContext context)
    {
        if(UnityEngine.Application.isPlaying)
        {
            var observer = new Entitas.VisualDebugging.Unity.ContextObserver(context);
            UnityEngine.Object.DontDestroyOnLoad(observer.gameObject);
        }
    }
```
But this doesn't:
```
    public void CreateContextObserver(Entitas.IContext context) {
        try {
            if (UnityEngine.Application.isPlaying)
            {
                var observer = new Entitas.VisualDebugging.Unity.ContextObserver(context);
                UnityEngine.Object.DontDestroyOnLoad(observer.gameObject);
            }
        } catch(System.Exception) {
        }
    }
```

**Comment by wistler** [comment]
I'm very much new to .NET projects, but it looks like the Unity project always has the `UNITY_EDITOR` symbol set; so after assembly, the DLL would only contain the first block when Visual Debugging is enabled for the project (i.e. when `ENTITAS_DISABLE_VISUAL_DEBUGGING` is _not_ defined), even before we access the DLL from the test project. (Because the assemblies seem to get compiled first, based on the individual project settings, before being linked to the test project.)

Looks like the intent of the `#if #else #endif` was to be able to compile the code block dependent on unity when run from within the Unity Editor, or the other block when compiled from outside the Unity Editor. However, the compilation always seems to use the symbols defined in the Unity-controlled .csproj file, which always has the UNITY_EDITOR symbol. 

Do we need to make another .csproj file (manually??) for the same production code-base (so that we can control the defined symbols), to compile the `#else` code block instead, for our unit test use cases?

**Comment by sschmid** [comment]
I'd be interested in a solution for windows. Works with mono on a mac, no security exception. Is this sth you can configure? Kind of trust a location / dll / sth ?
@wistler My setup:

- Unity project `Assembly-CSharp.csproj`
- A second Tests.sln which has a ref to `Assembly-CSharp.csproj`

This way I have the tests separate and not in a Editor folder which is great. `UNITY_EDITOR` shouldn't be an issue since

**Comment by KumoKairo** [comment]
Is this second sln inside the Unity root project folder?

**Comment by sschmid** [comment]
Added the suggested fix. Will be in the next release. Thanks!
