### ISSUE TITLE
How do I make changes to components?

### ISSUE THREAD

**Issue by boris-741** [sschmid/Entitas-CSharp#395]
How do I make changes to components?
I had a component and I wanted to change it:

`
public sealed class ViewComponent : IComponent {
    public GameObject gameObject;
}
`

to

`
public sealed class ViewComponent : IComponent {
    public Transform tr;
}
`

But I got a lot of compiler errors, although I fixed the code of all the systems.
I also tried to remove the generated code and generate it again, but without success

How to correctly change the members of a component?

**Comment by FNGgames** [comment]
Guide to regenerating code when making change to compoennts (upcoming changes to the code generator will likely improve this in future).

1. Move Components, Systems and GameController.cs to a folder outside your project (e.g. desktop).
2. Delete the contents of your Generated folder
3. Regenerate contexts (ctrl-shift-G)
4. Move Components folder back
5. ***Make changes to your components***
6. Regenerate components (ctrl-shift-G)
7. Move Systems and GameController.cs back and you're done.

**Comment by sschmid** [comment]
@boris-741 
The only thing you have to do besides fixing the code in systems (what you already did) is fixing the generated `GameViewComponent` (assuming your context is called game). The `AddView` and `ReplaceView` methods have to be updated to accept `Transform` instead of `GameObject`. No need to move files out of the project or sth like that. Deleting the generated folder will never help as the code generator cannot pick up any changes if there are compile errors.

@FNGgames is right, with the new roslyn code generator, it will be way better, since all you have to do is generate again and you should be fine.

Also see the wiki about fixing compile errors
https://github.com/sschmid/Entitas-CSharp/wiki/Code-Generator#fixing-compilation-errors

**Comment by sschmid** [comment]
@FNGgames I think your suggested workflow only works if components don't have any dependencies on you game code. As soon as a component uses a custom type in a field, it is getting more complicated. I think updating the generated code might be simpler

**Comment by FNGgames** [comment]
@sschmid All the code my components depend upon sit in my libraries folder next to the Entitas install, and I don't move it. If I use an enum for my componet, i declare it next to the component. I guess there's plenty of cases where this wouldn't be the case for people though.

**Comment by koden-km** [comment]
In my project I have been using some defines that I can set to disable all my Entitas code when making changes to components or systems.

It is a bit of extra work, but has has helped with refactoring and Entitas upgrades. I disable Systems while refactoring Components. Then after I regenerate the new components, I can enable systems again. It seemed a bit nicer than moving code in and out of the project.

```cs
#if !MYGAME_DISABLE_ENTITAS_COMPONENTS

public sealed class ViewComponent : IComponent {
   public GameObject gameObject;
}

#endif
```

And also one for systems.
```cs
#if !MYGAME_DISABLE_ENTITAS_SYSTEMS

public sealed class CommandLogicSystems : Feature {
    // ...
}

#endif
```

I added those defines to my Entitas source file templates to keep it easy.

**Comment by sschmid** [comment]
The new code generator is available. This will hopefully solve all your issues.

[Entitas on the Asset Store](https://www.assetstore.unity3d.com/#!/content/87638)
