### ISSUE TITLE
Fixed Update for Entitas

### ISSUE THREAD

**Issue by Shmewwww** [sschmid/Entitas-CSharp#402]
Hi! Can you give me advice how create system which executes in FixedUpdate;
I found not good solution for this:

```csharp
using Entitas;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

public class SomeFixedUpdateSystem : IInitializeSystem {

    public SomeFixedUpdateSystem(Contexts contexts) {
        
    }

    public void Initialize() {
        GameControlls.Instance.StartCoroutine(FixedExecute());
    }

    IEnumerator FixedExecute() {
        while(true) {
            
            // do something
            yield return new WaitForFixedUpdate();
        }
    }
}
```

**Comment by FNGgames** [comment]
Possible solution : Create a second set of systems in you game controller (e.g. Systems _fixedSystems = new Systems().Add() ...). Call _fixedSystems.Execute() from within FixedUpdate().

**Comment by sschmid** [comment]
Hey! Simply create systems that you execute `OnFixedUpdate()`

[Match-One - GameController](https://github.com/sschmid/Match-One/blob/master/Assets/Scripts/GameController.cs#L27) calls execute `OnUpdate()`. You won the systems, you can call them whenever is best for you.

I can also imagine having 2 sets of systems, one executed on Update, the other on fixed update.

Hole that helps

**Comment by sschmid** [comment]
@FNGgames you're just too fast ;)

**Comment by aefreedman** [comment]
(put this in the wiki) *cough*

**Comment by VladislavKostin** [comment]
Having some systems executed in Update and some in Fixed update was my first solution, but then doesn't it create problems with input?

For example, I create Input event entities in Input systems, and I clean them up on Cleanup(). If have systems in the Fixed update they won't receive the input, right? Or did I do something wrong? 

So instead I just Update my static FixedTime component on every FixedUpdate() and have my systems react to it.

**Comment by aefreedman** [comment]
It depends on how you implement your input system.

Ref. the [execution order of Unity events](https://docs.unity3d.com/Manual/ExecutionOrder.html) `FixedUpdate()` always occurs before `Update()`, even if executed multiple times.

So, if you create input entities in `Update()`, any `FixedUpdate()` system will not see that input _unless those systems are reactive_, in which case they should still react to changes to the input entity.

@VladislavKostin in your case, you're essentially turning any reactive system that reacts to a `FixedTime` component into what would be a `FixedUpdate()` script in default Unity, since that component will change at the rate of the physics timestep (which could be 20 times a frame...or not at all!)

**Comment by Shmewwww** [comment]
Okay!!! Create new system for fixed update doing well!! Thx

**Comment by VladislavKostin** [comment]
@aefreedman But If I create and cleanup (destroy) input entities inside an Update() than why does it matter if they are reactive? When are reactive systems triggered?  I thought reactive systems are triggered on Execute() and when it happens they receive all the accumulated changes from the collector.

**Comment by aefreedman** [comment]
@VladislavKostin yeah I'm wrong don't mind me lol
