### ISSUE TITLE
Clearing Groups and Resetting 

### ISSUE THREAD

**Issue by Xfer83** [sschmid/Entitas-CSharp#405]
Am attempting to implement the ability to "reset" the state of Match-One while remaining in play mode.
I ve looked at similar issues but keep getting the error:

>  ContextStillHasRetainedEntitiesException: 'Game' detected retained entities although all entities got destroyed!
> Did you release all entities? Try calling context.ClearGroups() and systems.ClearReactiveSystems() before calling context.DestroyAllEntities()

However I can't seem to figure out how to clear the groups, since context.ClearGroups() doesn't seem to exist in 0.41.2

Right now i am trying:
```
           _systems.TearDown();
           _systems.DeactivateReactiveSystems();
          _systems.ClearReactiveSystems();
          _contexts.Reset();
```
to stop things 

and anticipating using

```
            _systems.ActivateReactiveSystems();
            _systems.Initialize();
```

to restart them again.

**Comment by sschmid** [comment]
Hi! I blame it on the EntityLink. But to make sure, please select any of the empty entities in the hierarchy and see the "Retain" section of the Entity Inspector. It will tell you who is retaining the entity.

To reset Match One, remove and unlink the views first.

**Comment by sschmid** [comment]
Since it is just a simple example, this case has to be implemented first. Currently you have to add `DestroyedComponent` to properly destroy entities. Calling `context.DestroyAllEntities()` which is called for you if you call `contexts.Reset()` won't clean up the views

**Comment by karpinsn** [comment]
I ran into a similar problem on my game. You definitely need to remove the EntityLink but I also had to explicitly remove an EntityIndex that I had as well. This is kinda unfortunately because then I have to manually reset the EntityIndex since they are added to all contexts in InitializeEntityIndices as a post construction step.

**Comment by sschmid** [comment]
@karpinsn That's surprising. Was it a custom EntityIndex? Usually entity indices don't contain any destroyed entities.

**Comment by karpinsn** [comment]
Just one that I added to my component via the EntityIndex attribute

```csharp
using Entitas;
using Entitas.CodeGenerator.Api;

[Game]
public class LocationComponent : IComponent {
    [EntityIndex]
    public Location2D Location;
}
```

**Comment by sschmid** [comment]
Why do you have to remove that entity index manually? If an entity gets destroyed the LocationComponent will also get removed and therefore the entity will be removed from the index, right? But I see you're not on the latest version, can you tell me which version you are on, because I changed the context.Reset() behaviour recently, so I can check if you're affected

**Comment by sschmid** [comment]
I found the release with the change
https://github.com/sschmid/Entitas-CSharp/releases/tag/0.41.0

> Renamed Entitas.properties config keys
Removed context.DeactivateAndRemoveEntityIndices()
Removed context.ClearGroups()

**Comment by karpinsn** [comment]
Looks like I am on version 0.40.0. I can update if that will help. Otherwise I can try and put together a small example of what I am hitting.

As for what is happening I am calling Reset which is calling DestroyAllEntities. If I don't manually get rid of the entity index, they stay retained and at the end of the method it throws the ContextStillHasRetainedEntitiesException

**Comment by sschmid** [comment]
Since 0.41.0 `context.Reset()` won't deactivate the entity indices anymore, which is good. This didn#t make sense. So I guess upgrading will solve your issue already

**Comment by karpinsn** [comment]
Awesome, thanks. I'll upgrade and let you know if I hit any snags. Thanks for the great library

**Comment by sschmid** [comment]
I just updated my comment, I was wrong.

**Comment by Xfer83** [comment]
Went ahead and had RemoveViewSystem and DestroySystem implement ITeardown in order to remove the views and then destroy the objects properly when _systems.TearDown() is called.

This seems to work properly and maybe is the intended way to go about things.  (DId have to double check that i was Unlinking the views properly). 
Thanks !

**Comment by sschmid** [comment]
Awesome! Yes ITearDownSystem sounds like the perfect place to do it
