### ISSUE TITLE
context.CreateCollector(matcher, event) depreciated, example for replacement?

### ISSUE THREAD

**Issue by DTurley** [sschmid/Entitas-CSharp#412]
Just getting my head into Entitas and the fantastic project that it is.

A small issue I've has has been in following the 'Simple Entity View and Movement' tutorial, specifically Step 4.

View System seems to use the depreciated 'context.CreateCollector(matcher, event)' .The release notes say use 'context.CreateCollector(triggerOnEvent)' .Being totally unfamiliar with Entitas, I'm a little stumped as to what this should change to:

> `protected override Collector<GameEntity> GetTrigger(IContext<GameEntity> context)
>     {
>         return context.CreateCollector(GameMatcher.Sprite);
>     }`

Any help, greatly appreciated, thanks.

**Comment by T2RKUS** [comment]
https://github.com/sschmid/Entitas-CSharp/blob/develop/Tests/Unity/VisualDebugging/Assets/Examples/VisualDebugging/Systems/AReactiveSystem.cs - An example of a reactive system using the new changes, trigger on event.

https://github.com/sschmid/Entitas-CSharp/blob/develop/Tests/Unity/VisualDebugging/Assets/Examples/VisualDebugging/Systems/SomeMultiReactiveSystem.cs - An example of a multi reactive system using Trigger on event.

You won't be able to do that without generating code first though. Since it uses matcher generation code to make things shorter.

**Comment by T2RKUS** [comment]
Just put Added, Removed or AddedOrRemoved on the end of sprite. https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/Collector/TriggerOnEventMatcherExtension.cs

**Comment by DTurley** [comment]
Perfect, thanks a mill, I think I was having a compile issue that was also complicating the issue.  👍

**Comment by T2RKUS** [comment]
Awesome, If the problem has been solved please close this issue. :)
