### ISSUE TITLE
Suggestion on how to create a better network handler systems.

### ISSUE THREAD

**Issue by YimingIsCOLD** [sschmid/Entitas-CSharp#426]
There is 3 different way that I had came up with to handle my incoming tcp messages. I do not know which is the most efficient to do so. 

1. 
Create a component for each different message type I had, eg. HandshakeSuccessComponent with a incoming byte array field to hold the message. After that by having a HandshakeSuccessSystem to handle the incoming message. There will be a component and a system for each different message type.

2.
Create only ONE component called MessageComponent with a messageId field and incoming byte array. After that by having also just ONE system to handle the incoming message by a switch on the messageId field.

```csharp
protected override void Execute(List<NetworkEntity> entities) {
    foreach (var e in entities) {
        switch (e.message.Id) {
            case MCode.HandshakeSuccess:
                // Process the message.
                break;
        }
    }
}
```

3.
Similar to 2, create only ONE component called MessageComponent with a messageId field and incoming byte array. After that, create a system for each message type and do the filtering on the Filter method to handle the message.

```csharp
protected override bool Filter(NetworkEntity entity) {
    return entity.hasHandshakeSuccess;
}
```

**Comment by T2RKUS** [comment]
Personally, I'd go with option 2 (less components, less code. plus for each switch you could translate the message into a command for a command context). But I don't do much networking.

**Comment by YimingIsCOLD** [comment]
Thank you for your suggestion. I will go with option 2 too.

**Comment by sschmid** [comment]
Hi, I agree with @T2RKUS
This solution would be a mix of 1, 2 and 3.
- You'd have a command component for each message type, e.g. `HandshakeSuccessComponent`
- You'll have the system with the switch which only translates, meaning creating an entity and adding `HandshakeSuccessComponent`
- Having a HandshakeSuccessSystem

I think that will work and scale great because adding new message types is always the same workflow:
- add new component
- add new system
- modify switch statement

In the system with the switch you can then see all supported network message at a central place
