### ISSUE TITLE
Debug Information for Entities

### ISSUE THREAD

**Issue by PanCotzky** [sschmid/Entitas-CSharp#435]
Hey, Simon!

Yesterday, tried to get my game designer used to Entitas runtime debuging and encountered a pretty basic but unnoying problem. He can't guess what entity does what because they are not named.

At this point i realised that using Entitas debugging is a good way for game designers to test different things. It's almost a visual scripting. But they can't use it if they can't figure out what object does what. I need a basic method of naming entities in the debugger. I can do it pretty easelly in source version of Entitas but since it moved to binary philosophy I can't do that. So, it would be helpfull if you add something like this:

`var entity = someContext.CreateEntity("Unit_"+unitId);`

And then in the debugger it would look like

> "Unit_0"(some components)

If such functionality is already implemented, I apologise. But it is REALLY handy if you trying to work with game designers, level designers and level testers. Would appreciate if you add this functionality or explaned it to me if one is already implemented!

**Comment by FNGgames** [comment]
Hi, this is going to be a bit philosophical, so my apologies in advance:

An entity in the ECS architecture is completely generic, so the question "what type of *thing* is my entity" is inappropriate because in reality, *there is no spoon*. The *thingness* of an entity is an emergent property of the atomic components attached to it. There is no such thing as a car, only an entity with wheels, engine, steering wheel, windows etc.

The better way to think of it, is to ask "what group of components defines a *thing*". You can give your designer a cheat-sheet of these definitions. So if you compose a "player" entity by adding X,Y and Z components, your designer can refer to the cheat-sheet and find a player by searching "X, Y, Z".

If you know what the entity is supposed to be as you create it (which from your example, it looks like you do) you could add something like an `EntityTypeNameComponent(string name)` to the entity. Then the string would be visible as one of the components on the entity. This could be used by your designer as a way to verify he/she is looking at the right entities, but he/she would still need to search the heirarchy for the component names.

I guess what you're asking for is a way to get the value of that EntityTypeName string to appear in the GameObject's name in the hierarchy so you can avoid searching by components names - unfortunately i don't know if this is  possible - someone else might be able to answer that. 

One practical workaround is to have flag components specifically for the purpose of delineating these different kinds of entities (e.g. PlayerComponent - so your designer can search "Player"). While this is completely against what i understand to be the core principle of entity-component design, it should acheive what you need to make your designer's life easier.

**Comment by PanCotzky** [comment]
I see what you're saying, but all I need is some debug information. Naming the abstract entity may go against ECS philosophy but adding a comment to a bit of code is pretty standard for any programming philosophy and that's all I ask for.

**Comment by sschmid** [comment]
What about adding a Name-/Description-/DebugComponent with a name? Overriding `ToString` in components let's you do things like
<img width="467" alt="entitas-component-tostring" src="https://cloud.githubusercontent.com/assets/233700/19222457/0d295acc-8e59-11e6-9381-c890f1c60741.png">

**Comment by FNGgames** [comment]
or you could just override ToString ( i made things stupidly complicated sorry).
