### ISSUE TITLE
Feature request: both dll and src version in releases

### ISSUE THREAD

**Issue by c0ffeeartc** [sschmid/Entitas-CSharp#443]
Tried copy/paste sources from this repository as alternative to dll release, things didn't work.
Can there be separate zip with source version?

**Comment by sschmid** [comment]
Hi, I made the switch to deploy Entitas as dlls as of [Entitas 0.41.0](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.41.0)

Deploying Entitas as Dlls instead of source code which has multiple benefits, e.g.
- Entitas Unity menu appears even if code doesn't compile
- Enables 3rd party Addons and Plugins
- Enables command line code generator

It's been a while, so I can't recall what is not working with the sources, but I think with some minor changes I should work (I might be wrong, this change is almost half a year ago :))

Is there a specific reason you want to use the sources?

If you want to make changes, I recommend forking and building Entitas locally. This enables you to run the tests too. See [CONTRIBUTING.md](https://github.com/sschmid/Entitas-CSharp/blob/develop/CONTRIBUTING.md)

**Comment by KumoKairo** [comment]
I've found a huge downside of DLL version.
As all game code goes through the DLL which is not debuggable by default, Unity fails to connect its profiler correctly on a target device. All code of systems get's "squished" into one line of general "Update" loop with overall time. There's no way to expand it and see what's going on inside, thus making profiling on a target device very hard.
Editor profiling is not representative because of the Debug Systems that generate some overhead (additional allocations and execution time)
Target device profiling is hard (almost impossible) because DLLs are not expandable.

I see two ways around it.
First - provide an additional debug version of DLLs along with the release ones. I still need to check whether it will work for the profiler or not
Second - use a source version.

I've checked my considerations with a few people and each of them had the same result.
https://imgur.com/wu3nPFt.png

**Comment by kdrzymala** [comment]
You can disable the visual debugging in the preferences window. That should help with profiling in the editor, shouldn't it?

**Comment by KumoKairo** [comment]
Not really, it still has side effects. And anyways, profiling in the Editor is just a first step. Devices have different runtimes and different behavior, not to mention that devices are usually more picky to some code that may run good in the Editor and not so good on the target device. Rule of thumb is to actually profile on a target device.

**Comment by kdrzymala** [comment]
What side effects? I'm doing it this way and didn't notice overhead.
I hear you, though I tend to profile in the editor since deep profile isn't working on devices reliably anyway.

**Comment by KumoKairo** [comment]
I'll get back to this issue once I have the numbers. Stay tuned

**Comment by KumoKairo** [comment]
I did some digging with visual debugging turned off and it looks like there's really no additional overhead in the editor. However, I can't really check it on a device to compare non-visual debugging version in the editor and actual release version on a device.
@kdrzymala it really seems that the editor profiling with visual debuggin turned off is the only option for now, thanks for the feedback.

I'll need to try a few more things:
1. Build a debuggable version of Entitas `.dll` files (not visual debugging, just script debugging so it may display in the Unity profiler)
2. Get back to making a working copy of sourced Entitas version

**Comment by sschmid** [comment]
I can imagine providing an additional debug version of DLLs along with the release ones . Would that fix it?

**Comment by KumoKairo** [comment]
I'll try it in the following week and write here on the results

**Comment by KumoKairo** [comment]
Ok, rebuilding the core `Entitas` project as a debuggable version doesn't change anything, it's still doesn't show a full callstack in the profiler.

I'll try rebuilding the whole set of Entitas projects and see if it makes a difference.

**Comment by KumoKairo** [comment]
I've rebuilt the whole Entitas library as a Debug version but it doesn't change anything.

I guess the only way left is to use SRC version. I'll try to "sourcify" the core Entitas project first, the one that contains all the systems and common execution logic.

**Comment by KumoKairo** [comment]
Ok, I've made a working source version of Entitas. 
As it turns out, Entitas doesn't have a lot of dependency on .dlls. It just needs to load `Data Providers Plugins`, `Code` and `Data` generators from assemblies. It also checks the current Entity version by the `Entitas` .dll.
I've made it look for certain interfaces in the currently loaded assembly instead and provided a fake version for it (it just needs it to suggest updating)

But you know what - sourced version of Entitas doesn't really help a lot either. Profiler shows the same picture as it is with the .dll version of Entitas. So the root of the problem is not really in it's "dllness", it's somewhere else. I've double checked that the built project doesn't contain separate .dlls and it's all in one usual `Assembly-CSharp.dll`:
![image](https://user-images.githubusercontent.com/2943071/31291345-3ed0a34a-aad8-11e7-9dde-73544c0ecf60.png)

I'll continue digging further

**Comment by KumoKairo** [comment]
I've implemented a simple extension of `Systems` class, `DevelopmentSystems`, which use `Profiler.BeginSample(<system name>)` and `Profiler.EndSample()` on builds with a "development build" tick. The results are promising-profiler shows the whole deep callstack down to almost every call, even if building it on a device. It may even work with the .dll version of Entitas, I'll go check it now and update this comment
![default](https://user-images.githubusercontent.com/2943071/31311893-beb35256-abbe-11e7-9000-af96da0d8fe1.png)

**Comment by optimisez** [comment]
@KumoKairo It's really nice and must have feature. Kindly submit a PR.
