### ISSUE TITLE
Status of Entitas?

### ISSUE THREAD

**Issue by yamlCase** [sschmid/Entitas-CSharp#450]
What is the current status of Entitas?  I saw that Simon made a commitment to work full time on Entitas starting July 1st, but have yet to see any activity since then (from anybody).  I'm hoping that the devs have their heads buried in code and just haven't come up for air yet.

**Comment by T2RKUS** [comment]
Well... I haven't been working on Entitas but I have been working on my own take of the Entitas Code Generator with YAML support (to replace Entitas-Lang since @mzaks is not currently working on it)
https://github.com/T2RKUS/Spark 

So, while the core of Entitas may not have had an update (as far as github goes) the community is still quite active. Be sure to come by Entitas-CSharp Gitter chat more often. Entitas users post ideas and code about how they do things in their games/apps. gitter.im/sschmid/Entitas-CSharp

**Comment by jwvanderbeck** [comment]
What is the relation with Entitas in the Asset store for $45?

**Comment by chiuan** [comment]
still alive.

**Comment by GreatVV** [comment]
@sschmid Can you make any update about status of entitas? Because I just want to have new version )

**Comment by sschmid** [comment]
Currently wrapping up everything needed for the new release with the new code generator. Waiting for the last feedback tomorrow. Finding good mic recording levels for Tutorial Videos in the meantime ;) Looking good so far. Next release ETA this October. Currently testing in Unity 2017.2, all seems to work fantastic :)

**Comment by sschmid** [comment]
I can literally feel 1.0 in the air... :)

**Comment by sschmid** [comment]
<img width="557" alt="entitas-issuesclosed" src="https://user-images.githubusercontent.com/233700/32524218-f71379a0-c41e-11e7-94e1-d2b1f327e9de.png">

Does this image answer your question? :)
