### ISSUE TITLE
Building dll's failed

### ISSUE THREAD

**Issue by nwben** [sschmid/Entitas-CSharp#456]
We are working with the entitas source code in our project. If we are trying to build the Entitas dll with a high strict level the build getting failed.
The reason is that your code is calling an obsolete method.
Context.cs line 367
void onDestroyEntity(IEntity entity) {
   DestroyEntity((TEntity)entity);
}

It is possible to fix it? Otherwise we have to change your code to build the dll.

Thx
nwben

**Comment by sschmid** [comment]
Hi!
Yes this can easily be fixed:

`context.DestroyEntity(e)` is obsolete since 0.42.0 in favour of `entity.Destroy()` ([see code here](https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Context/Context.cs#L167))

Simply inline the method [DestroyEntity L:168](https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Context/Context.cs#L169-L198) in `onDestroyEntity ` [L:367](https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Context/Context.cs#L367) and remove the obsolete method `DestroyEntity `

**Comment by sschmid** [comment]
`context.DestroyEntity(e)` will remain in the next couple of releases for backwards compatibility

**Comment by nwben** [comment]
Thx for your answer
