### ISSUE TITLE
Inconsistent Matcher.AnyOf behaviour with Collectors

### ISSUE THREAD

**Issue by Fejuto** [sschmid/Entitas-CSharp#467]
I'm getting some unexpected behaviour on collectors in combination with an AnyOf Matcher. AddComponent and RemoveComponent appear to work as expected. But ReplacingComponent inconsistently gives different behaviour.
```c#
    void Test(Contexts contexts) {
        var c = contexts.game.CreateCollector(GameMatcher.AnyOf(GameMatcher.Position, GameMatcher.Name));
        var e = contexts.game.CreateEntity();

        Debug.Log(c.count); //0
        e.AddPosition(0);
        Debug.Log(c.count); //1 as expected; entity entered the group

        c.ClearCollectedEntities();
        Debug.Log(c.count); //0

        e.AddName("hi");
        Debug.Log(c.count); //0 as expected; entity didn't enter the group. It was already in it.

        e.RemoveName();
        e.AddName("hi2");
        Debug.Log(c.count); //0 as expected; entity didn't leave nor enter the group.

        e.ReplaceName("hi2");
        Debug.Log(c.count); //expected 0 but getting 1.
    }
```

(The issue cascades into ReactiveSystems)

**Comment by KumoKairo** [comment]
https://github.com/sschmid/Entitas-CSharp/issues/378

**Comment by vladpazych** [comment]
I can confirm the issue. 

If entity already has a `NameComponent`, replacing it with the new value will trigger change, but it certainly should not (because entity is already in the group because of `PositionComponent`).

And if you remove `NameComponent` before adding it again - it will **not** trigger change, as expected.
