### ISSUE TITLE
EntitasHierarchyIcon: null texture passed to GUI.DrawTexture

### ISSUE THREAD

**Issue by PencilBow** [sschmid/Entitas-CSharp#477]
Just upgraded to Entitas 0.42.5.

Running my current project produces the following warnings:
![image](https://user-images.githubusercontent.com/18717967/32360091-0e8c4a28-c053-11e7-9ecf-cce390087aa6.png)

Turning off visual debugging gives different output
![image](https://user-images.githubusercontent.com/18717967/32360251-40c40f7a-c054-11e7-9c5b-bfeb04d683b6.png)

It might be related to https://github.com/sschmid/Entitas-CSharp/issues/476#issuecomment-341614265 ?

**Comment by sschmid** [comment]
Can you try right clicking on the Entitas folder and reimport?

**Comment by sschmid** [comment]
Did it help?

**Comment by danielbe1** [comment]
I had the same exact issue and deleting the Entitas folder, then reimporting helped,

**Comment by sschmid** [comment]
Sometimes Unity seems to lose the labels. The images are labeled. Reimporting always helped when I had this problem

**Comment by PencilBow** [comment]
I will test it out and let you know once the new CodeGenerator is on the assetstore.

**Comment by sschmid** [comment]
Feel free to reopen if you still have this issue

**Comment by PencilBow** [comment]
update for future reference: removing all files and plugging in the new codegenerator fixed all the issues. I'm going to guess that reloading would be fixed the initial issue.

**Comment by ethankennerly** [comment]
For others reading a warning every frame:  I also did not see the icon beside the game object in the hierarchy window.  The above steps alone did not fix my setup.  I also had to find and restore an old copy of the `Assets/Entitas/Editor/Images`.  Somehow when I installed the asset store version, the images got deleted.  I already had the GitHub version installed before, so perhaps the images got merged into old location which I cleaned due to conflicts with the new version.  On the import window from the asset store, there is a tiny warning icon on the editor images folder that has the following tooltip:  `Will override existing asset, which may be undesirable.`
