### ISSUE TITLE
timing of group change

### ISSUE THREAD

**Issue by wallpap3r** [sschmid/Entitas-CSharp#511]
I have a task system to run task, and when the task is done, add a task_done_flag to the entity which run the task. It may code like this:

```csharp
void OnConnected (Entity e){
    e.isTaskDone = true;
}
```
and a group is got like this:
```csharp
_grp = ctx.GetGroup(
    Matcher.AllOf(
        Matcher.Task, Matcher.TaskDone)
   .NoneOf(Matcher.Destroyed));
_grp.OnEntityAdded += OnTaskDone;
```
and the function OnTaskDone will add destroyed flag to the entity:
```csharp
void OnTaskDone(group, entity, index, ...){
    entity.isDestroyed = true;
}
```
the problem is after I set the isDestroyed flag, it will also trigger grp.OnEntityAdded. It seems the NoneOf condition is not work when I change the entity in the delegate logic.

**Comment by sschmid** [comment]
Hey,

always prefer Reactive Systems over direct Group delegates when possible. This will already fix your issue.

Caution is advised when using direct group delegate that include NoneOf like in your case. Explanation:
You will probably have a system that destroys entities that are `entity.isDestroyed = true`. Destroying an entity will remove all its components one by one. Depending on the order of the removal this entity might trigger group delegates. In your case it seems like DestroyedComponent is remove first which will make the entity enter the group again. Right after it will leave the group again because Task and TaskDone will get removed too, but you delegate has already been called.  Using a Reactive System with a Filter will fix this and is recommended.
