### ISSUE TITLE
[Question] Code generation with errors

### ISSUE THREAD

**Issue by zendorx** [sschmid/Entitas-CSharp#513]
Hi,
I have an question. How do I can regenerate entitas without Roslyn plugin? Is there any solution? I accidentally generated wrong component and seems I cannot remove it without fixing all code manually. Even worse if project became big and I need to do some refactoring. Why does Entitas code generation depends on compile errors at all? 

Second question. Is Roslyn plugin a panacea?

I very like Entitas, but this limitation is very painful.

Cheers

**Comment by sschmid** [comment]
Hi,
the previous code generator relies on reflection which means it produces source code based on a compiled dll. Compile errors in your code prevent you from building a new dll which means recent changes in the code cannot be picked up by the code generator since it will process the previous dll.

The roslyn plugin from the asset store doesn't use reflection and makes it possible to generate even if there compile errors.

Entitas Asset Store:
https://www.assetstore.unity3d.com/#!/content/87638

Video Demo:
https://www.youtube.com/watch?v=LGKsqSg5FHg

Jump to the actual demo in the Video:
https://youtu.be/LGKsqSg5FHg?t=17m0s

**Comment by zendorx** [comment]
Yeah, looks great, but I'll wait some discount :)

One more question, can I use Entitas with some Dependency Injection framework(Zenject for example) or there no need?

**Comment by sschmid** [comment]
Personally, since I switched to Entitas I never used any DI frameworks anymore, and I never felt the need. Systems usually get the contexts ref via the constructor and then they have access to all data and dependencies.
I also use sth we call Services, where we extract logic that might be used by multiple different systems, e.g. BuildingService or CharacterService. So all systems only need the contexts and some services. This can be easily handled without a DI framework. But of course, if you prefer you can still use it. But if you ask me, try without first and see if you like it

**Comment by zendorx** [comment]
Thx, great! Also I  see potential to make some sort or repository of systems or commands that very common in use.
