### ISSUE TITLE
Jenny gen in Unity does not generate components, but CLI does

### ISSUE THREAD

**Issue by DianeOfTheMoon** [sschmid/Entitas-CSharp#526]
I would expect that they should work exactly the same.

**Comment by sschmid** [comment]
Just to be sure, have you seen the 2 assumptions I've made in #519?
When you say you use Unity to generate, I assume you use the reflection based generator and there's no need to use the CLI. When you say you use the CLI I assume that you use the Entitas.Roslyn plugin, because this is not supported by Unity yet.

**Comment by DianeOfTheMoon** [comment]
I mean the menu option Jenny -> Generate, which I would assume to the be the same as `Jenny.exe gen` and different than Entitas->Generate.

**Comment by sschmid** [comment]
As I've seen from your previous issue, I see you're using Roslyn. Unfortunately roslyn doesn't work in Unity yet because it's using new .NET frameworks. This is why you have to use the CLI for now. You cannot generate with the green generate button from Unity. While it should theoretically do the same no matter if in Unity or not, there are some differences and limitations when run in Unity. But I think once set up correctly, the workflow with generating right from the IDE is faster and more convenient anyway.

See the video from #492
