### ISSUE TITLE
Attribute to add a component to ALL contexts

### ISSUE THREAD

**Issue by jwvanderbeck** [sschmid/Entitas-CSharp#533]
I don't know if this is doable, but it would be great if you could decorate a component in some way as to automatically make it available to all contexts without explicitly doing this.

Reason for the request is you have some components that are just common ones used across all contexts, and right now explicitly marking them means if you change the contexts in the future, you have to ensure you hunt all them down and update the decoration or else get odd bugs.  If there as something akin to `[AllContexts]` then whenever you generated your code, it would update on its own and no bugs :)

**Comment by T2RKUS** [comment]
Since the contexts are defined in the properties file you could modify the existing data provider to take that new attribute into account. It's definitely doable. see https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Plugins/Entitas.CodeGeneration.Plugins/DataProviders/Components/Providers/ContextsComponentDataProvider.cs

You wouldn't need to modify the existing code generators but not sure how you'd do it with the Roslyn code generator since I use my own.

**Comment by sschmid** [comment]
ref #444

**Comment by sschmid** [comment]
I usually prefer explicit over implicit. I get the idea, but there are also reason not to use [All]. Example: if you add a new context you never know which components it will contain. Before that it might have made sense for a component to be in all, but not in the new one.
But it's a good reason to start looking into writing custom data providers and generators :) You can add a new data provider for components which will add all contexts if it has [AllContext] attribute
