### ISSUE TITLE
get_gameObject can only be called from the main thread

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas-CSharp#573]
Sometimes I will get this error message after changing scene. Any idea why come out this error?

```
get_gameObject can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.Component:get_gameObject(Component)
Entitas.VisualDebugging.Unity.EntityBehaviour:onEntityReleased(IEntity)
Entitas.Entity:Release(Object)
Entitas.Collector`1:ClearCollectedEntities()
Entitas.Collector`1:Deactivate()
Entitas.ReactiveSystem`1:Deactivate()
Entitas.ReactiveSystem`1:Finalize()
```

![image](https://user-images.githubusercontent.com/7009368/35204260-ef4656c8-ff67-11e7-953f-ef6d3bdabbee.png)

**Comment by KumoKairo** [comment]
It's because there's a `Deactivate` call in the `Collector's` finalizer https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Collector/Collector.cs#L135

Finalizer are called by GC right before the destruction of the object. This call happens in a separate thread, this is why we can't access anything unity-specific there as it will fail to do it correctly. 

Finalizers in C# are usually used for closing unmanaged resources like files and handles, they are not really suited for general stuff, especially that's connected to Unity.

It's usually not a problem because collectors are immortal throughout the game, they basically never die (don't get garbage collected), but once you start having stray ones or using a Unity editor for it, it starts to be a problem

The only solution is to remove all finalizers completely as they are not the feature that has to be used for the purpose they currently serve. 

Take this Collector for example. We call `Deactivate` in the finalizer. https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Collector/Collector.cs#L79
What `Deactivate` does is just unsubscribing from groups events. But events are GC hooks in C#, so if any group is alive, Collector won't be picked up by GC at all. On the other hand, if all groups are dead and we don't have any references to a collector, it will all be Garbage Collected together without the need of unsubscribing from events because GC cleans up the whole chunk of objects together (so this finalizer is just some pure useless work)

I have pointed this problem out back in the day, but it was decided to let it be.

**Comment by optimisez** [comment]
So, for the time being before we get better solution just call ```DeactivateReactiveSystems``` before ```TearDown``` should fix the problem?

```
private void OnDestroy()
    {
        systems_.DeactivateReactiveSystems();
        systems_.TearDown();
    }
```

**Comment by sschmid** [comment]
Fyi, this can only happen in the editor. This won't happen on the device. VisualDebugging is editor only and will be stripped out for release builds. Properly cleaning up manually first as suggested can avoid this exception.

**Comment by sschmid** [comment]
see #438
Will close and mark as duplicate
