### ISSUE TITLE
What about a group event 'WillRemove'?

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#597]
Hey,

The reason is to be able to access the component's data right before it is removed, what are your thoughts on this?

Example: I've got a TargetComponent which holds a target ID, and on it being added the target is retained, but when I want to release the target, I need to either create a flag willBeDestroyed and use that to reference the component or hold a list and iterate over it to confirm it being removed, so I think having this event will be of great benefit for certain things.

Cheers

**Comment by sschmid** [comment]
With the common practice of using systems and reactive system all access is basically deferred. I strongly advise to not use group events directly on a regular basis, only if you're aware of the potential consequences. It's a very common practice to have a DestroyedComponent to flag entities as destroyed. This way all systems still have access to all the data before the entity will be destroyed for real in on of the last systems.

**Comment by sschmid** [comment]
btw, group.OnEntityRemoved will give you access to the removed component

**Comment by bit-chimp** [comment]
When you say group events directly what exactly do you mean?

This is the approach I've started using with Triggers

````
     protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context)
        {
            return context.CreateCollector(GameMatcher.Target.AddedOrRemoved(), GameMatcher.AIState.AddedOrRemoved(), GameMatcher.MoveComplete.Added());
        }
````

Do you mean events like OnEntityRemoved etc?

**Comment by FNGgames** [comment]
@sschmid i think the point of this question to ask for a reactive system trigger that fires at the same time as Removed() currently does, but that gives the reactive system access to the component that just got removed.

That is: we know we can get the component from the .Removed() *event* but we want it in the reactive system so we can process it before it gets deleted.

@bit-chimp In my case I work around this by having a lot of intermediate components (e.g. adding **RemoveThingComponent** instead of actually removing **ThingComponent**. Then i can write an RS that reacts on **RemoveThing.Added()** which then processes the data in the ThingComponent and finally, actually calls e.RemoveThing().

**Comment by sschmid** [comment]
You have 3 options:
- Flagging an entity with a component like DestroyedComponent (common practice)
- using group.OnEntityRemoved
- using entity.OnComponentRemoved
