### ISSUE TITLE
Question about which system to use

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#603]
Hi,

I was wondering whether it would be better to use an IExecuteSystem or a ReactiveSystem? I think a ReactiveSystem is more optimised but I'm not sure.

````
using System.Collections.Generic;
using Entitas;
using Entitas.CodeGeneration.Attributes;
using UnityEngine;

namespace Assets.Sources.Physics.Logic
{
    public class GravitySystem : ReactiveSystem<GameEntity>
    {
        private float m_gravity = .98f;
        public GravitySystem(Contexts contexts) : base(contexts.game)
        {
        }

        protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context)
        {
            return context.CreateCollector(GameMatcher.OnGround.Removed(), GameMatcher.Velocity.Added());
        }

        protected override bool Filter(GameEntity entity)
        {
            return entity.isOnGround == false;
        }

        protected override void Execute(List<GameEntity> entities)
        {
            foreach (var entity in entities)
            {
                var velocity = Vector2.zero;

                if (entity.hasVelocity)
                {
                    velocity = new Vector2(entity.velocity.x,entity.velocity.y);
                }

                if (velocity.y < m_gravity)
                {
                    velocity.y += m_gravity;
                }

                entity.ReplaceVelocity(velocity.x, velocity.y);
            }
        }
    }
}
````

Cheers

**Comment by FNGgames** [comment]
So, I think they work out the same - i think if you know you are going to process every entity with component X, every frame, there's no reason not to use an execute system with a group, and loop over group.GetEntities() every frame.

I also sometimes do it your way: a reactive system that calls Replace() every frame, so it "feeds back" the entities into itself. The only reason i do it this way is because i can then use multi-reactive systems, and make these things work across all contexts. If you only need one context, there is no downside to using group.GetEntities() every frame.

**Comment by bit-chimp** [comment]
Didn't think of it like that, thanks man!

**Comment by FNGgames** [comment]
Advantage of GetEntities() is that it's always exactly up to date so there's no need for the extra logic performed in .Filter() in an RS - presence of the components from your group is guarenteed as long as you consume the entities right after you call GetEntities().

**Comment by bit-chimp** [comment]
Definitely, it all makes sense now, I'll start using it more often :)
