### ISSUE TITLE
New Entitas Architecture - Actions and Commands?

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#638]
Hi,

I'm looking into the new architecture and was wondering if someone could provide me with some examples? Example, how it would work with AI Movement? 

AI.MoveRequest
AI.MoveRequestActionService
MoveComponent
MoveSystem

Would that be the way to do it? Or would it be better to validate in a separate AI system (in my case GOAP)

Cheers

**Comment by FNGgames** [comment]
I do it similarly to the way you have suggested, i have a SteeringRequestComponent -> RequestSteeringSystem -> Async calculations -> SteeringResultComponent -> ApplySteeringForceSystem.

For pathfinding on a grid or navmesh I'd do it the same way: PathRequest -> Async pathfinding -> PathResult -> FollowPathSystem. 

If you're using GOAP or a behaviour tree this pattern still works, BehaviourRequest -> GOAP Pathfinding -> BehaviourResult -> DoBehaviour.

**Comment by bit-chimp** [comment]
And the reason for doing this is to create a central validation system?

**Comment by bit-chimp** [comment]
Why use a Service rather than a ReactiveSystem for example?

In the Match One Demo, AddViewSystem was replaced with a ViewService which listens for the adding of an AssetComponent, how is that different to having a ReactiveSystem which reacts to the same component?

**Comment by StormRene** [comment]
@bit-chimp @FNGgames is doing this, because he uses multi threading. He put's his data with Request into his threaded systems and after a certain time he gets Result back. 
The Service is a abstraction to decouple unity from entitas. So no unity specific logic is in entitas and vice versa. So the view/unity can react on added asset without entitas knowing there is something that draws the data.

**Comment by bit-chimp** [comment]
That makes sense, thanks!

**Comment by FNGgames** [comment]
For me, services are these "outside" sources of information or functionality. I have a recent example where the service pattern and interfaces really helped me out:

For example I have an `interface IInputService` and it has properties like `Vector2D LeftStick {get;}`. My game doesn't care what is providing the left stick data, it just needs to be able to ask something for it when it needs to. I started off with `UnityInputService : IInputService` where i had an implentation like `Vector2D LeftStick { get { return new Vector2D(Input.GetAxis('horizontal'), Input.GetAxis('Vertical'); } }` but then later I bought InControl from the asset store. The advantage of this pattern is that all i had to do was write a new `InControlInputService : IInputService` using the InControl api, and feed that in at the start of the game instead of the unity one. There's nowhere in my game code that touches either Unity or InControl, so literally nothing changes in the game code when i change the way i get input. It's that sort of flexibility that's really useful.

**Comment by bit-chimp** [comment]
Thank you for your input guys, that cleared it up for me.
