### ISSUE TITLE
Failed to install Entitas to Unity 2017.3.1f1 

### ISSUE THREAD

**Issue by tonypig1988** [sschmid/Entitas-CSharp#670]
Hi,

I import Entitas from AssertStore.Then I open the UI of Preferences... and click the button of "Auto improt".But it doesnt work.

**Comment by sschmid** [comment]
On which Unity version are you?

**Comment by tonypig1988** [comment]
Unity 2017.3.1f1 (windows)

**Comment by sschmid** [comment]
Unity 2017.3 has known UI issues. See #583

> Solution: Don't click "Continue and Overwrite" with the mouse, but use the enter key on your keyboard.
(I know, sounds weird, but works)

**Comment by tonypig1988** [comment]
I just try Unity 2017.2.0f3.
the same issues.
and I use the enter key on my keyboard on Unity 2017.2.0f3.but it still doesnt work.
I am Installing Unity 2017.3 and try it again.

**Comment by sschmid** [comment]
Are there errors in the console? Entitas should definitely work with your Unity version. Btw, if you plan to use the roslyn code generator plugin, simply press the `Auto-Import` file contained in the Jenny.zip.

See
https://www.youtube.com/watch?v=L-18XRTarOM

**Comment by tonypig1988** [comment]
and I use the enter key on my keyboard on Unity 2017.3.1f3.but it still doesnt work

**Comment by sschmid** [comment]
I suggest closing the Entitas Preferences Window, open it again, and then use the enter when auto importing. If that doesn't work, it shouldn't really matter, because I think you will use the roslyn generator anyway which you setup by double-clicking the Auto-Imprt file, after you unzipped Jenny.zip into your project root folder as shown in the video

**Comment by tonypig1988** [comment]
it is done! thank you very much!

**Comment by sschmid** [comment]
Glad it worked!
