### ISSUE TITLE
Unload unnecessary systems

### ISSUE THREAD

**Issue by yanjingzhaisun** [sschmid/Entitas-CSharp#674]
Hi,

I wonder if we have some sort of functionality that some of the systems can be turned off during runtime.

Take tower defense as an example. The players can first build their bases, then start the game to defeat the enemies. Apparently those building related systems are not needed during the fight.

**Comment by surferau** [comment]
you can separate systems into different steps. 

_systemsAlwaysToExecute.execute();
if(GameStateService.condition== true)
  _systemsExecuteWhenCondtionIstrue.execute();

**Comment by sschmid** [comment]
I see 3 common ways to do this:

1. Systems know themselves when to execute
```csharp
class MySystem {

   void Execute() {
        if (context.isInBattle) {
             // Battle logic
        }
    }
}

```


2. Systems are managed by the parent system

```csharp

public sealed class UpdateSystems : Feature {

    readonly Contexts _contexts;

    public UpdateSystems(Contexts contexts) {
        _contexts = contexts;

        Add(new MySystem(contexts));
        // add other systems
    }

    public override void Execute() {
        if (_contexts.game.isInBattle) {
            base.Execute();
        }
    }
}

```
Instead of hardcoding the condition you can also create a GuardSystem which takes a function to check a condition, so the GuardSystem can be reused for multiple scenarios.

3. What @surferau suggested

**Comment by thygrrr** [comment]
I just place the System Initialize and Update calls in a separate GameObject / MonoBehaviour.

That can then be easily enabled or disabled.

**Comment by StormRene** [comment]
I highly recommend the first solution that simon wrote, because it's not necessary to turn off and on a system if it's only executed if the required conditions are met. It's really helpful to see in what condition the system is executed by trigger/filter, instead of debugging down the road to know which system is which enabling or disabling or worse execution is dependent on some unity monobehaviour state. Especially if you have a big game. 
It's not a big deal to have many thousand systems at the same time if they are reactive and not getting executed all at the same time.
