### ISSUE TITLE
Noobish Question with 2018.1

### ISSUE THREAD

**Issue by kenofori** [sschmid/Entitas-CSharp#695]
Hi,

I have a have question. I just found out Entitas accidentally and interested to both learn and use it. However Unity 2018.1 also have ECS and i want to understand what'd be difference in both? will Entitas make use of 2018's ECS or not.

In short, as a noobie, should i learn Unity's ECS first or Entitas?

Cheers

**Comment by sschmid** [comment]
Hi @kenofori,

Entitas and Unity ECS are both implementations of Entity Component System Architecture. They share a lot of the same concepts, the implementation is different though.

As you might have seen from the YouTube videos, we introduced Entitas back in 2015 already. My advise that I can give you on what to learn first strongly depends on your goals. If you want to build and release a game this year, I recommend using Entitas. It's production ready, has been around for some years and is battle tested on multiple platforms like PC, mobile, VR, etc. There's a healthy community which can help and answer questions. There are also a bunch of helpful features that are not available in Unity ECS, like Reactive Systems and Entitas Events. We developed a lot of conventions and guidelines to solve most of the problems already, which is a huge benefit in my opinion.

Unity stresses that their ECS is not production ready, but if you want to learn ECS I think it's worth checking out. Also, if you know that your game will require heavy multithreading, Unity ECS will be a great option because of their tight integration with the C# Job System. Keep in mind that apis might change in the future and that best practises will develop over time.


@mzaks wrote a blog post about features that you find in Entitas which he misses in Unity ECS

https://medium.com/@icex33/my-wish-list-for-unity3d-ecs-1f3985bbe308

**Comment by kenofori** [comment]
@sschmid 

Thank you for your detailed reply.
Is there any plans to eventually base it on Unity's ECS (even in future)

Whats the difference between github and asset store version?

**Comment by sschmid** [comment]
You're welcome.

There are currently no plans to do so. But since I use Entitas professionally on a daily basis, I will keep it up to date and will improve it whenever I see potential enhancements. It's quite possible that Entitas can benefit from things like NativeArrays and the C# Job System

**Comment by kenofori** [comment]
Last question, please do know that im coming from a noobish background so want to clear the confusion. 
I took the 2016 session you guys did and saw you using foreach instead of for loop. (isnt foreach generate garbage and slow).
I'm convinced to go with your framework due to stability and production, especially its on sale and hopefully learning it will also help me switch to Unity'e ECS when it becomes stable after a year.

**Comment by StormRene** [comment]
quote from the unity page: "foreach loops
In versions of Unity prior to 5.5, a foreach loop iterating over anything other than an array generates garbage each time the loop terminates. This is due to boxing that happens behind the scenes. A System.Object is allocated on the heap when the loop begins and disposed of when the loop terminates. This problem was **fixed in Unity 5.5**."

**Comment by kenofori** [comment]
Thanks, i have started the documentation, v impressed with performance comparisons  :)
will come back here for any further questions
