### ISSUE TITLE
calling RemoveListener in event handler causes InvalidOperationException

### ISSUE THREAD

**Issue by christianvoigt** [sschmid/Entitas-CSharp#698]
Event systems simply use a foreach loop to call all listeners in the listener list. If one of these listeners removes itself from this list while being called by the EventSystem, this will cause the following error: 

`InvalidOperationException: Collection was modified; enumeration operation may not execute.`

I think this is not a fringe case so it should be supported. Listeners should be able to decide during an event notification that they are no longer interested in being notified. 

One solution would be to copy the list with `toList()` in the foreach loop, another would be to call the listeners in reverse.

**Comment by cywil4** [comment]
I have same here. In my example I can't unregister from the event while game object is being destroyed.

**Comment by TargetDetected** [comment]
Same problem here.

**Comment by FNGgames** [comment]
@TargetDetected The listener component holds a list of IListener objects. `AddThingListener(IThingListener item)` is a shortcut for adding a listener to a list of listeners, which is why you can add mutliple identical ones. When the listener system executes it iterates the list of listeners inside that component and calls their OnThing() method - this was the solution for how to add mutliple listeners to the same entity.

Could the RemoveListener method actually flag a listener for removal internally, then have the removals done at the end of the event system in question. Maybe RemoveListener adds a lsitener to a hashset somewhere and once the inital loop is finished, event system could loop the "flaggedForRemoval" set and remove them? IDK how workable that is but it's a suggestion that would allow us to keep the current API without having to use actions.

**Comment by christianvoigt** [comment]
I think a good solution would be to add new listeners to the start of the list and iterate over them in reverse order. That way you still call listeners in the order they were added, but you do not have make a copy of the listener list every time the event is emitted (which could happen every frame). The addListener methods would become slightly slower, but normally they are not called every frame.

**Comment by c0ffeeartc** [comment]
reverse order won't work when listener deletes other listener not self

**Comment by TargetDetected** [comment]
Right... well, list copy then. Listeners almost useless if you can't remove them anyways.

**Comment by TargetDetected** [comment]
https://files.gitter.im/sschmid/Entitas-CSharp/mqCF/Entitas.CodeGeneration.Plugins.dll  In case someone needs this - i added .ToArray() for EventSystems listeners firing, so you can now safely modify collection (call remove listener in the event handler)

**Comment by sschmid** [comment]
`.ToArray()` works and is a fast and simple solution. But it will also allocate memory every frame for every event system. I'd like to avoid this, because I think in the majority of cases, we don't need that functionality and I don't want to have a general performance penalty.
I will probably first try copying to a buffer list. Not 100% happy with this solution, because of the double iteration. But I will add it so people can use the feature and keep it in mind. Maybe we can come up with a better solution.

I was also thinking about Unity's NativeArray, but I think you cannot use it without Unity.

**Comment by cywil4** [comment]
@sschmid Did you consider use Action instead of array?
