### ISSUE TITLE
Component value change in Inspector doesn't use entity componentPool

### ISSUE THREAD

**Issue by ifshuaishuai** [sschmid/Entitas-CSharp#73]
I found out when change a component's value when game running in Unity Inspector, the event OnEntityRemoved and OnEntityUpdated doesn't work. The first one get call with Component's value already changed. The last one get call with previousComponent equals to newComponent. I wonder if it is an issue.

**Comment by sschmid** [comment]
Yes, I see... VisualDebugging is not yet updated to use the new entity componentPool. By updating components with the inspector, the actual values of the component get modified. The same changed component is then used when calling entity.ReplaceComponent(). That's why you currently see that previous and new components are the same instance.
I'll work on updating VisualDebugging to use the componentPool too and to ensure expected behaviour.
Good find! Thanks for letting me know

**Comment by sschmid** [comment]
This has been fixed in [Entitas 0.29.0](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.29.0)

**Comment by ifshuaishuai** [comment]
Nice work, I'll try that out. :)
