### ISSUE TITLE
Where and how should I write methods that use in many systems?

### ISSUE THREAD

**Issue by Noicon** [sschmid/Entitas-CSharp#738]
I read the cook book, still don't figure it out.

Should that be
```csharp
Class Funtion()
{
    public static void nextid()
    {
        //calculate next id
    }
}
```
or write them in [Unique] component?

**Comment by RomanZhu** [comment]
There is a Service pattern https://github.com/sschmid/Entitas-CSharp/wiki/How-I-build-games-with-Entitas-%28FNGGames%29

I implemented this one in my old template https://github.com/RomanZhu/Match-Line-Entitas-ECS/blob/master/Assets/Sources/Services/ElementService/ElementService.cs

That's how I use those Services https://github.com/RomanZhu/Match-Line-Entitas-ECS/blob/master/Assets/Sources/GameController.cs

**Comment by sschmid** [comment]
Hi,

here's a discussion about that
#609

Here's how I use services in Match One
https://github.com/sschmid/Match-One/tree/master/Assets/Sources/Services

Here's how the services is used in a system
https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Systems/Game/Systems/GameBoard/Systems/FillSystem.cs

Personally, I use my own DI solution instead of `.singleton`, but the idea remains the same.

I don't use static helper methods, because you cannot mock them in unit test or partially override them.

**Comment by RomanZhu** [comment]
@sschmid Nice timing :D 8 seconds difference :D

I like that hiding Service behind interface, easy to mock/change engine/change pathfinding asset/etc.
I just pass that Services blob into system constructor, it is easy to track down and understand how everything works

**Comment by Noicon** [comment]
.singleton is work-well and simple enough.
Thank all of you :D
