### ISSUE TITLE
Is Entity/Component order deterministic?

### ISSUE THREAD

**Issue by ip** [sschmid/Entitas-CSharp#768]
Hi. I'm trying to implement a deterministic lock-step simulation using Entitas. Given that my systems are deterministic, can I rely on the order of Entities and Components, or I should add a special `EntityId` component etc. to ensure this myself? This include methods of Entity, Context, Group, Collector.

If it is deterministic, will it remain like this in the future?

The library is great, by the way. 😃

**Comment by sschmid** [comment]
@ip Entitas uses HashSet<TEntity> for entities in contexts and groups. I remember my tests for determinism suggested that contexts and groups (and therefore systems, reactive systems and collectors) are deterministic.

I suggest to find out if hashsets are really deterministic, because I have the impression that there are different opinions on that. Again, my tests show, they are, but you're invited to prove me wrong.

On that note, Entitas is not ordered or sorted, meaning, entities won't necessarily be iterated in the order they were created - deterministic, but not ordered.

**Comment by ip** [comment]
Thank you for the answer. I just realized that the consistent order isn't actually needed, I can deterministically calculate the Context's hash by hashing entities and sorting their hashes.
