### ISSUE TITLE
Take snapshot of current contexts used to roll back to a specific moment

### ISSUE THREAD

**Issue by simonynx** [sschmid/Entitas-CSharp#772]
Hi,

I am working on a lockstep synchronized game, now client may need to predict several frames prehead to Server. When the prediction goes wrong, Client would need to revert the predict frames, then simulate the confirmed frames from Server, which would require contexts rolling back to an exact state before.  

My plan would be to save all entities and its components of current contexts. When it needs to revert, modify the contexts to the one saved.

However, I found it hard to implement, since Context cannot get Entity from a specific CreateIndex, and GetComponents would not return the index of a component.

Any suggestions about how to take snapshots of and revert Context would be appreciated.

Cheers

**Comment by wallpap3r** [comment]
If I get it correctly,I think you need "EntityIndex" to query things created. you can search some tutorials for this topic.

**Comment by sschmid** [comment]
Rolling back to a snapshot for every wrong prediction sounds pretty intense. Depending on the size of your contexts, this might be a expensive thing to do. What about saving important data + framecount in the prediction, so you're able to undo the prediction and recalculate from a specific framecount?

**Comment by simonynx** [comment]
@sschmid thanks for the reply. I thought that would not need to take a snapshot for every frame, but like per 15 frames. Then revert to that shot, recalculate inputs and fast forward to the present. As you said, saving the important data of the prediction still needs to pick out Context changes, likely which entity destroyed or created or component data changes. For rolling back, the exact Entity should be reverted according to saving data.  Any good solution to that?  Would it be appropriate to add a GUID component for the coming search?  Or other methods. Thanks a lot.

**Comment by simonynx** [comment]
@zhuchun yeah, you are right. I misunderstand the term of Lockstep. However, I still need Snapshot to roll back to a specific moment. You seem to be experienced to fast-paced sync game, have you tried converting one with Entitas? Thank you so much.

**Comment by zhuchun** [comment]
@simonynx Check this [video](https://www.youtube.com/watch?v=ueEmiDM94IE&t=2192s), the developer of Rocket League has explained lots of details and references on his speech. Personally speaking, it's hard to approach authoritative FPS when your team is lack of developer/time because the requirements and workload are significantly higher than a single player game. Entitas/ECS didn't make it harder, Overwatch is using ECS by the way.

You can find a few(yes, not much) famous articles written by Valve and other developers, they're old but still the backbone of almost everything. The most recent games you can learn from are Rocket League and Overwatch, their developers have made excellent talks.

**Comment by simonynx** [comment]
using CreateIndex to link entity and save all necessary components. Compare with entities of the current context, revert the difference.
