### ISSUE TITLE
Further improve entity memory footprint

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#78]
Storing components in a dictionary is slow, that's why Entitas is using arrays and stores components at a certain index. This is super fast for the cost of memory, because each entity is created with an array with a capacity of the total number of components. Currently we can use multiple pools and assign components to one or more pools with Attributes like [Core] or [UI] to minimize the initial capacity of the array.
It would be nice to find or create a data structure which doesn't need a initial capacity and can grow while at the same time reaches array-like performance.

**Comment by sschmid** [comment]
@mzaks @cloudjubei @arne-schroppe

**Comment by arne-schroppe** [comment]
I still think that a hash map with lazily created heaps as values is a promising idea. The hash function could simply be bit-masking on the component id. So every component id that ends in e.g. `0b010` would end up in the same heap.

But we need to keep in mind that this is not a completely uniform hash function, since the number of components will probably not be something that ends in all 1's, so everything below `num_component_ids & 0b111` will potentially have one more entry. And the hash table itself also needs extra memory, so we might even end up using _more_ memory with this method.

One way to mitigate this could be, that we expect the heaps not to be filled up completely. So to go with the current example, if we hash with the last three bits and thereby potentially have 8 entries per heap, we would at first only allocate space for 4 entries, hoping that the remaining slots will never be used. Whether that is a good idea and what numbers to use exactly is something we'd have to measure in a couple of real applications.

All in all I'm not sure if this is worth it, though. We might end up using more memory and we're going from 1 `O(1)` access + 1 dereference to  `O(log n)` access + 2 dereferences (first from hash table to heap and then from heap entry to component data). But it sure sounds like a fun experiment :)

**Comment by arne-schroppe** [comment]
Actually now that I think about it: @antonlicht's idea of simply using a heap sounds way better. We would start with a capacity for maybe 20% of the total number of components (the best percentage would still need to be measured in real applications). This means that we might need to reallocate, but that should ideally not happen too often. Access would still be `O(log n)` instead of `O(1)` but even with 200 different components that would be at most 8 comparisons, so not really much.

**Comment by sschmid** [comment]
Will close becaus of #112
