### ISSUE TITLE
GetEntities() order different in two client.

### ISSUE THREAD

**Issue by XiaoJueMing** [sschmid/Entitas-CSharp#820]
Hi,

I have an found a problem
Here's some code

 var characterGroup = context.GetGroup(GameMatcher.Character);
        return characterGroup.GetEntities();

when i run this in two client ,the "characterGroup.GetEntities() " has two  entity  and the create  order is same in server.
but their order is different in two client. it very confuse me , please help me..

Cheers

**Comment by StormRene** [comment]
Hello XiaoJueMing and welcome to the community,
You cannot rely on the order for the return value of the _GetEntities_ method, because the entities are stored internally in the group as _HashSet_. For your problem there are surely several solutions. If you describe the case to me I can surely help you :)

**Comment by sschmid** [comment]
@XiaoJueMing 
StormRene is correct. Generally there is no order in groups and reactive systems. If your logic relies on a specific order you can sort them before processing them, e.g

```csharp
protected override void Execute(List<TestEntity> entities) {
    foreach (var e in entities.OrderBy(e => e.creationIndex))
    {
         // do sth       
    }
}
```
