### ISSUE TITLE
Entitas Asset Store vs Entitas Github for Photon Bolt

### ISSUE THREAD

**Issue by artfabrique** [sschmid/Entitas-CSharp#829]
Hi,
I have a question.
I'm making a Unity game with Photon Bolt (headless auth. server) and I'm very confused about Entitas Asset Store version.
I don't understand do I need it or not? Can you help me to make a decision?

**Comment by artfabrique** [comment]
Anybody? Please!

**Comment by sschmid** [comment]
The asset store version comes with the roslyn code generator which is strongly recommended because it works when there are compilation errors in your code. It will save you a lot of time and you will have no issues generating code.

**Comment by zhuchun** [comment]
Regarding Photon Bolt, I'm not sure how are you going to make it works with an ECS implementation. It's a well-made framework comes with its own code generator, which means you have to organize your code in traditional style, otherwise, you may have problems when trying to use EntityBehavior/GlobalBehavior. You can try the Github version first, it's free and fully functional, the asset store version is better though.
