### ISSUE TITLE
IReactiveSystem does not differentiate between AddComponent and UpdateComponent

### ISSUE THREAD

**Issue by Noshire** [sschmid/Entitas-CSharp#89]
An IReactiveSystem will always react to Components that have been either added (AddComponent) or updated (UpdateComponent).

I was just wondering if this is by design or not.

I understand that components are treated as immutable, so it makes sense to treat every component modification / replacement as a delete + add for outside observers.

Still I was wondering if there is some way to distinguish these events - or if that is even code smell in the frame of ECS. To give an example, I have a SpriteResourceLoaderSystem. It reacts to AddComponent<SpriteResourceComponent> and instantiates a new ViewComponent with a GameObject+SpriteRenderer with the correct sprite.

If I modify the component through code or visual debugger at runtime, each change gets treated as a delete + add. Subsequently, the whole gameobject would be destroyed and recreated each time.

I did a workaround now where the system checks if the iterated-upon Entity already has a view component. If not it is created, if it has one it is simply updated (e.g. the SpriteRenderer modified).

I'm not sure though if I'm on the right track there. Should I just strictly always regenerate objects, even if it's more expensive than it needs to be? Or would it make sense to provide separate events for Add vs UpdateComponent?

Thanks for your inputs!

**Comment by sschmid** [comment]
Hi, you are right, there is no difference between adding or updating a component. This is by design. Systems contain the logic to represent the current state of your pool. If a component got added OR replaced doesn't matter. All that matters is the fact that is currently there.

What you described as a workaround sounds like a common thing to do for me. I do the same in my current project :)
I have an AddViewSystem, its only job is to display the correct Sprite depending on the ResourceComponent.name. Always showing the correct Sprite means:
- If there is no GameObject yet, create one and set the Sprite
- If there is a GameObject, update the Sprite
