### ISSUE TITLE
Is Entitas abandoned?

### ISSUE THREAD

**Issue by JJCaballeroSt** [sschmid/Entitas-CSharp#938]
Hi, I have been studying Entitas for a couple of months and it seems the best option right now when using entities on Unity (even over the "official" entity system, ugh, using gameobjects to be able to use entities...), but I can only see that the last time this project was updated was a year ago. So I can only wonder... is this project totally abandoned by their developers? I mean, as a developer I know that a library with the size of Entitas it's not ever totally done, there's always something new to add...

(Not being the same case at all, but it's pretty worrysome, because is the biggest library of its kind on Unity (the other being... the OTHER Unity maybe? Using Unity on Unity... maybe I should have to try that and make a XZibit meme with that...) I also have seen a pretty similar pattern with Zenject (a very well made library about dependency injection) with the big difference of their original mantainers being a bunch of dicks when someone took the library and started working on improvements on his own.

**Comment by FNGgames** [comment]
Hi, it seems like @sschmid the author and maintainter has gone quiet and has perhaps abandoned the project. That being said, Entitas's core is pure csharp and has no dependency on unity so it's not going to stop working with newer unity versions and it was essentially feature-complete when it was last updated. I guess feel free to decide for yourself what that means for you. I'm currently using it on an in-production commercial product and I would probably use it again in future projects even without Simon maintaining it.

**Comment by sschmid** [comment]
Hi
long time no see :)
I haven't been active for a while, that might continue for a few months due to my current focus on Popcore. But I haven't abandoned Entitas. At Popcore we're using it every day for all our games and we releasing many games a months with it. We're super happy with Entitas and it's very stable.
I think Entitas is safe to use, battle tested and doesn't require much maintenance atm. I really can't wait to come back to Entitas and give it some deserved love, until then I don't see a reason not to use it. It's production ready and you can modify it easily if necessary at all.

**Comment by JJCaballeroSt** [comment]
Thanks for the info, @sschmid! Thanks for all your work in this cool library! I'll be using it in my next projects!

**Comment by FNGgames** [comment]
@sschmid so great to hear! Hope you're well.

**Comment by sschmid** [comment]
Lots of activity again 🤩 see #1005
