### ISSUE TITLE
[Suggestion] Don't have OnEntityAdd / OnEntityRemove be called on a Replace

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#97]
One of things that has flustered me as work on my Entitas project is that there is no good way to hook into when a component is added for the first time or removed altogether. This is because the `OnEntityAdded` and `OnEntityRemoved` are also called whenever a component is updated.

The code I am referring to is in Group.cs:

``` csharp
public void UpdateEntity(Entity entity, int index, IComponent previousComponent, IComponent newComponent) {
    if (_entities.Contains(entity)) {
        if (OnEntityRemoved != null) {
            OnEntityRemoved(this, entity, index, previousComponent);
        }
        if (OnEntityAdded != null) {
            OnEntityAdded(this, entity, index, newComponent);
        }
        if (OnEntityUpdated != null) {
            OnEntityUpdated(this, entity, index, previousComponent, newComponent);
        }
}
```

I understand that the goal was to build something along the lines of functional idiom where components are pseudo immutable in terms of the API but I've found the omission of this functionality limiting. Especially when, if say `OnEntityRemoved` or `OnEntityAdded` are not called on a update the functionality still exists by using `OnEntityUpdated` instead.

I could just be missing a better way to do this so let me give a concrete example from my game. I have an invincibility component that I add to my player entity when it gets hit so it can't be immediately hit again. The invincibility component contains a timer that use a reactive system to countdown and when it reaches zero I clear the invincibility flag. I'd like to be able to disable the collider component on my player when he is invincible and then re-enable when the invincibility window has passed.

Now I can think of a few different ways to accomplish this, but the cleanest way that popped to mind was having the collider be disabled when the component is first added and then enabled when it is removed. Since I am using a timer, the `OnEntityAdded` and `OnEntityRemoved` would be called constantly. So I have a few other options off the top of my head:
- Disable the collider when I add the invincibility component, enabled when I remove it. I am not a huge fan of this because this places the collider responsibility in two separate systems.
- Have the reactive system check if the collider is enabled and disabled it if it is. This seems like a lot of wasted look ups in all cases besides the first reactive call that enabled the system.
- Separate the timer and the invincibility flag into two components. This is probably what I will do, and I think you could make the argument that it is the "right" thing to do, but it's another component and sometimes I feel like I have components coming out of my ears. :laughing: 

This would obviously be a huge breaking change but it's just something I wanted to start a discussion about it and get your thoughts. Thanks for taking the time to read all this.

**Comment by sschmid** [comment]
Ah, I see, I got it after reading it again... The problem is that your InvincibilityComponent has a field for the timer and you update the component each frame. Ok, you obviously don't want to add yet another TimerComponent but instead store the timeout in the InvincibilityComponent. I guess that's fine, too.
I think it's currently possible to have one ReactiveSystem with Matcher.Invincibility.OnAddedOrRemoved(). In the execute you can do
```csharp
var collider = e.view.gameObject.GetComponent<Collider>();
if (e.hasInvincibility) {
    collider.enabled = e.invincibility.timer == 0;
} else {
    collider.enabled = true;
}
```
This code will set the collider active if the InvincibilityComponent  has been removed completely or the timer is over. Otherwise the collider is disabled.
Does that make sense?

**Comment by grygus** [comment]
Sschmid but this code still will be called every component replace right? Wouldn't it be better if it would be called just on first component Add and last Removed? Right now for this kind of stuff I do not use e.Replace but just access fields directly e.ticksLeft-- ,but this breaks reactive approach :(

**Comment by JamesMcMahon** [comment]
Yeah I didn't want to muddy the waters with that example. The crux of my point was that if they aren't fired on an update, add and replace become a lot more useful.

**Comment by sschmid** [comment]
@grygus You should never do sth like e.ticksLeft--, it circumvents all the cool features built into Entitas.
I repeat: You should never do sth like e.ticksLeft-- ;)

Yes, it will be called every time. There is no such thing as adding the first time or remove it, because even if you remove a component there might be another system just adding it.You cannot know if sth got removed or replaced. But you can always check on your own with e.hasComponent.
I like how @mzaks explained it in the talk: You should be able to pause the game at any given time, look at the pool and you should be able to reason about the data. That means: either an entity has a component, or it doesn't. Adding sth the 'first time' would be implicit knowledge which isn't reflected anywhere and cannot be reasoned about. If you need this kind of information, then - yes - you'd put it on a component :)

**Comment by sschmid** [comment]
@JamesMcMahon Imagine, we would have these kind of behaviour with added and removed.
Case 1:
- The timer ran out
- you remove the component
- Ok works

Case 2
- The timer ran out
- you remove the component
- Collision happens
- you add again (same frame)
- meh, doesn't work anymore
- got event removed, but got a new component

**Comment by sschmid** [comment]
But since I heard this idea before, I'll think about it again and try to find cases where it might make sense. No guarantee though ;)

**Comment by sschmid** [comment]
@JamesMcMahon I'm sorry for your ears ;) but actually, your last point 'Separate the timer and the invincibility flag into two components' is the way to go in my opinion, it solves all the problems, plus you can reuse the TimerComponent for other things, too

**Comment by grygus** [comment]
@sschmid I know I should't but it really hurts when I know that code is called every update even when it doesn't need to :) but i see your point. I also do not like this kind of separation of things for me invincibility flag and timer are one thing and it should be one component. What if i would need fly timer shoot timer.. number of components is growing really fast :)

**Comment by sschmid** [comment]
@grygus what you just said is actually an argument for slitting it into 2 components, because then you have less components because you reuse the TimerComponent for each task. It also solves calling the code each frame, because you only react on invincibility added or removed. Win win :)

**Comment by grygus** [comment]
@sschmid hmm did I missed something? can I have 3x TimerComponent on one Entity? :)

**Comment by sschmid** [comment]
Oh, that's what you mean, nope :)

**Comment by JamesMcMahon** [comment]
Sorry, I started this chain and then got distracted by other obligations.

>Adding sth the 'first time' would be implicit knowledge which isn't reflected anywhere and cannot be reasoned about.

First time was a bad choice of words. To clarify, Add would only be called if a component is added and doesn't already exist on the current entity. Remove would only be called if it is not being replaced.

>Yes, it will be called every time. There is no such thing as adding the first time or remove it, because even if you remove a component there might be another system just adding it.

Yeah there could be some nasty complexity there. Systems would need to be more careful about using replace versus add. It still seems more useful to me then having `OnEntityAdded` being essentially interchangeable with `OnEntityUpdated`.

>I'm sorry for your ears ;) but actually, your last point 'Separate the timer and the invincibility flag into two components' is the way to go in my opinion, it solves all the problems, plus you can reuse the TimerComponent for other things, too

Thats actually what I ended up doing. What do you mean by "reuse the TimerComponent"? Are you referring to using a base class? I actually have several components with timer related functionality in my codebase.

**Comment by grygus** [comment]
I came up with another nasty thing that is happening right now in this state of events. When your system depends on the state of previous component you supossed to subscribe to OnUpdate hovewer if Add is still called you usually end up with doing similar things twice first in OnAdd and than in OnUpdate you make some modifications based on previous state and can call methods from OnAdd one more time, what can do further complications.

**Comment by sschmid** [comment]
Ok, I'll think about this again, maybe there's room for improvement :)

**Comment by dkozlovtsev** [comment]
Can we please have separate Add, Update, Replace in reactive systems as far as i can tell Entity class already supports this, but the info is lost when pool calls UpdateEntity in Group class. 
My use case:
I have a Target component:
```
public class Target : IComponent
{
    public Vector3 coords;
    public Vector3 rotation;
}
```
It is  attached to units, and provides the target for it to move to.
For debug purposes i want to draw small sphere on target location, right now it is next to impossible without changing component structure, because on every Replace both Removed and Added callbacks are triggered, and i have no way of knowing whether it was Removed to be Added again(so i need only to update transform of the view) or it was Removed for good and i need to destroy the view.

**Comment by JuDelCo** [comment]
How you flag your units to destroy them?

Check this:  https://github.com/sschmid/Entitas-Shmup/tree/master/Assets/Sources/Features/Spawn

**Comment by dkozlovtsev** [comment]
@JuDelCo  i have the structure very similar to Shmup( not a big surprise considering i was refering to it while developing mine =) ), but i'm not talking about showing unit, the one thing that helps the case of showing unit (and destorying it) is that it uses separate components to indicate that Entity needs to shown( `Resource` in Shmup) and other component to store View, and notify it about position changes(`View` component in Shmup). Again, i use the same approach and it makes sense for unit.

Further in the development i've added TargetComponent, which is used by MoveSystem to move Unit. If i am to use the same approach to show Target as to showing Units, i need to create additional components(TargetResourceComponent and TargetView), i need to change how target is added(as it needs to also add TargetResourceComponent), how it is deleted(To delete TargetResourceComponent) and have a set of systems that adds, removes, and updates TargetView based on what happens to TargetResource and Target components. That is a lot of changes to add for a simple debug drawing.

**Comment by JuDelCo** [comment]
Why you can't reuse the same Resource and View components (and systems) for the target ?

**Comment by dkozlovtsev** [comment]
>Why you can't reuse the same Resource and View components (and systems) for the target ?
Because Target is on the same entity as original Resource and View components

**Comment by JuDelCo** [comment]
How about storing a dictionary of resources in ResourceComponent and a dictionary of Views on ViewComponent ?

```csharp
// In ResourceComponent
Dictionary<IComponent, string>  //  string == resource name

// In ViewComponent
Dictionary<IComponent, IViewController>
```

Of course adapting the systems as well

**Comment by dkozlovtsev** [comment]
As a workaround it works, aside from look-up for every position change even for the non-debug view. But it is a workaround. I still support adding separate OnAdd, OnUpdate, OnRemove so that it would be possible to do things in a more straightforward way

**Comment by Deepscorn** [comment]
> How about storing a dictionary of resources in ResourceComponent and a dictionary of Views on ViewComponent ?
```csharp
// In ResourceComponent
Dictionary<IComponent, string>  //  string == resource name
```

What will be with game saving then? Looks like that will ruin "entities is game state" statement.

@JamesMcMahon, 
> there is no good way to hook into when a component is added for the first time or removed altogether. This is because the OnEntityAdded and OnEntityRemoved are also called whenever a component is updated

Don't think it will help in you example usage, but just FYI. You can easily hook to entity add / remove. See https://github.com/mikecann/Entitasteroids/blob/master/Assets/Entitasteroids/Scripts/Sources/Features/Level/LevelEndingSystem.cs:
```csharp
_pool.CreateEntity()
                .AddAge(0)
                .AddMaxAge(2)
                .OnEntityReleased += OnLevelEndTimerReleased;
```
It is to wait 2 seconds before going to next level so user can understand what's going on. As you see, usage of such a thing is very limited because it is not persistent between save-load. Things change if you add an id to such entity and perform a look up instead of creating new entity
