### ISSUE TITLE
Group return different order of entities

### ISSUE THREAD

**Issue by YimingIsCOLD** [sschmid/Entitas-CSharp#98]
At first, I created entity 1, 2, 3, 4 and all had a common component. So when I use pool.GetGroup() it return a list containing those entities in a order of 1, 2, 3 and 4. 

However, after removing the common component and created another 4 new entity with the same common component, I used pool.GetGroup() and it return a list with a order of 4, 3, 2 and 1. Did I miss out any code or this is how it work?

**Comment by mzaks** [comment]
The order of entities is non deterministic, if you need a deterministic behaviour you would need to sort them yourself. This is due to the fact that entities are stored in the group in a HashSet due to performance reasons. 

https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/Group.cs#L33

**Comment by sschmid** [comment]
Weeeell, starting with a new HashSet the order is deterministic - but it's not sorted. Usually if you process entities in a system, the order doesn't matter. If it does, you have to order them own your own, either based on a sortable identifier component or the creation index.

**Comment by sschmid** [comment]
And yes, since it is a hashset the order in which you add entities most likely is not the order in which you read them
