### ISSUE TITLE
Entitas creates a "[username].userproperties file" when running

### ISSUE THREAD

**Issue by haltingstate** [sschmid/Entitas-CSharp#996]
When running the code generator from unity an empty file is created.

-[username].userproperties

This should be fixed. The file is useless, not used anywhere and can be committed into git by accident. The file depends on username the person is login as.

**Comment by sschmid** [comment]
Hi @haltingstate 
This is intentional behaviour based on the `Preferences` class.
`. userproperties` should be added to `.gitignore`

The idea of user properties is that user setups might be different and you can overwrite keys based on your system.
You can also reference keys from the user properties in your main properties, e.g.:

```
Unity.Path = /Applications/Unity/Hub/Editor
Unity.App = ${Unity.Path}/Unity.app/Contents/MacOS/Unity
```

If your system is setup differently, you can overwrite `Unity.Path` in your user properties
